# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Correlation2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CrossCore(object):
    def setupUi(self, CrossCore):
        CrossCore.setObjectName(_fromUtf8("CrossCore"))
        CrossCore.resize(800, 600)
        self.CrossCore_2 = QtGui.QWidget(CrossCore)
        self.CrossCore_2.setObjectName(_fromUtf8("CrossCore_2"))
        self.gridLayout = QtGui.QGridLayout(self.CrossCore_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.CrossCore_2)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.MainTab = QtGui.QWidget()
        self.MainTab.setObjectName(_fromUtf8("MainTab"))
        self.listpath = QtGui.QTextEdit(self.MainTab)
        self.listpath.setGeometry(QtCore.QRect(10, 70, 381, 31))
        self.listpath.setObjectName(_fromUtf8("listpath"))
        self.tempfilename = QtGui.QTextEdit(self.MainTab)
        self.tempfilename.setGeometry(QtCore.QRect(10, 160, 381, 31))
        self.tempfilename.setObjectName(_fromUtf8("tempfilename"))
        self.targetfilename = QtGui.QTextEdit(self.MainTab)
        self.targetfilename.setGeometry(QtCore.QRect(10, 230, 381, 31))
        self.targetfilename.setObjectName(_fromUtf8("targetfilename"))
        self.ynlist = QtGui.QCheckBox(self.MainTab)
        self.ynlist.setGeometry(QtCore.QRect(10, 40, 96, 22))
        self.ynlist.setObjectName(_fromUtf8("ynlist"))
        self.infobox = QtGui.QTextBrowser(self.MainTab)
        self.infobox.setGeometry(QtCore.QRect(10, 280, 761, 201))
        self.infobox.setObjectName(_fromUtf8("infobox"))
        self.correlate = QtGui.QPushButton(self.MainTab)
        self.correlate.setGeometry(QtCore.QRect(629, 240, 131, 29))
        self.correlate.setObjectName(_fromUtf8("correlate"))
        self.return_2 = QtGui.QPushButton(self.MainTab)
        self.return_2.setGeometry(QtCore.QRect(639, 10, 121, 29))
        self.return_2.setObjectName(_fromUtf8("return_2"))
        self.fitdegree = QtGui.QSpinBox(self.MainTab)
        self.fitdegree.setGeometry(QtCore.QRect(510, 240, 71, 31))
        self.fitdegree.setMinimum(1)
        self.fitdegree.setObjectName(_fromUtf8("fitdegree"))
        self.label_6 = QtGui.QLabel(self.MainTab)
        self.label_6.setGeometry(QtCore.QRect(430, 230, 71, 51))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.MainTab)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.MainTab)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 151, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.MainTab, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.settings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(269, 259, 511, 231))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editor = QtGui.QTextEdit(self.horizontalLayoutWidget)
        self.editor.setObjectName(_fromUtf8("editor"))
        self.horizontalLayout.addWidget(self.editor)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.settings)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(270, 200, 501, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reset = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.horizontalLayout_3.addWidget(self.reset)
        self.save = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_3.addWidget(self.save)
        self.listoforders = QtGui.QListWidget(self.settings)
        self.listoforders.setGeometry(QtCore.QRect(0, 301, 91, 181))
        self.listoforders.setObjectName(_fromUtf8("listoforders"))
        self.addout = QtGui.QPushButton(self.settings)
        self.addout.setGeometry(QtCore.QRect(100, 420, 161, 31))
        self.addout.setFlat(False)
        self.addout.setObjectName(_fromUtf8("addout"))
        self.SaveProfile = QtGui.QPushButton(self.settings)
        self.SaveProfile.setGeometry(QtCore.QRect(190, 459, 71, 31))
        self.SaveProfile.setObjectName(_fromUtf8("SaveProfile"))
        self.Lowertext = QtGui.QLineEdit(self.settings)
        self.Lowertext.setGeometry(QtCore.QRect(100, 300, 71, 29))
        self.Lowertext.setObjectName(_fromUtf8("Lowertext"))
        self.uppertext = QtGui.QLineEdit(self.settings)
        self.uppertext.setGeometry(QtCore.QRect(190, 300, 71, 29))
        self.uppertext.setObjectName(_fromUtf8("uppertext"))
        self.label = QtGui.QLabel(self.settings)
        self.label.setGeometry(QtCore.QRect(100, 350, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.settings)
        self.label_2.setGeometry(QtCore.QRect(190, 350, 66, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.SaveProfile_2 = QtGui.QPushButton(self.settings)
        self.SaveProfile_2.setGeometry(QtCore.QRect(100, 460, 71, 31))
        self.SaveProfile_2.setObjectName(_fromUtf8("SaveProfile_2"))
        self.SystemProfiles = QtGui.QComboBox(self.settings)
        self.SystemProfiles.setGeometry(QtCore.QRect(10, 50, 241, 25))
        self.SystemProfiles.setObjectName(_fromUtf8("SystemProfiles"))
        self.UserProfile = QtGui.QComboBox(self.settings)
        self.UserProfile.setGeometry(QtCore.QRect(10, 110, 241, 25))
        self.UserProfile.setObjectName(_fromUtf8("UserProfile"))
        self.useUser = QtGui.QCheckBox(self.settings)
        self.useUser.setGeometry(QtCore.QRect(10, 150, 151, 22))
        self.useUser.setObjectName(_fromUtf8("useUser"))
        self.label_3 = QtGui.QLabel(self.settings)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.settings)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.AddProfile = QtGui.QPushButton(self.settings)
        self.AddProfile.setGeometry(QtCore.QRect(19, 200, 231, 29))
        self.AddProfile.setObjectName(_fromUtf8("AddProfile"))
        self.lineEdit_3 = QtGui.QLineEdit(self.settings)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 160, 331, 29))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.line = QtGui.QFrame(self.settings)
        self.line.setGeometry(QtCore.QRect(260, -20, 20, 541))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.settings)
        self.label_5.setGeometry(QtCore.QRect(270, 160, 91, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.open = QtGui.QPushButton(self.settings)
        self.open.setGeometry(QtCore.QRect(700, 160, 71, 31))
        self.open.setObjectName(_fromUtf8("open"))
        self.ProfileName = QtGui.QLineEdit(self.settings)
        self.ProfileName.setGeometry(QtCore.QRect(20, 260, 231, 29))
        self.ProfileName.setObjectName(_fromUtf8("ProfileName"))
        self.label_9 = QtGui.QLabel(self.settings)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 91, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        CrossCore.setCentralWidget(self.CrossCore_2)
        self.menubar = QtGui.QMenuBar(CrossCore)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        CrossCore.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CrossCore)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CrossCore.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(CrossCore)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        CrossCore.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(CrossCore)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CrossCore)

    def retranslateUi(self, CrossCore):
        CrossCore.setWindowTitle(_translate("CrossCore", "MainWindow", None))
        self.ynlist.setText(_translate("CrossCore", "Use List?", None))
        self.correlate.setText(_translate("CrossCore", "Correlate", None))
        self.return_2.setText(_translate("CrossCore", "Return", None))
        self.label_6.setText(_translate("CrossCore", "Degree->", None))
        self.label_7.setText(_translate("CrossCore", "Path To Template file", None))
        self.label_8.setText(_translate("CrossCore", "Path To Target file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("CrossCore", "Main", None))
        self.reset.setText(_translate("CrossCore", "Reset Text", None))
        self.save.setText(_translate("CrossCore", "Commit Changes", None))
        self.addout.setText(_translate("CrossCore", "Add ignore range", None))
        self.SaveProfile.setText(_translate("CrossCore", "Save", None))
        self.label.setText(_translate("CrossCore", "Lower", None))
        self.label_2.setText(_translate("CrossCore", "Upper", None))
        self.SaveProfile_2.setText(_translate("CrossCore", "Delete", None))
        self.useUser.setText(_translate("CrossCore", "Use User Profile", None))
        self.label_3.setText(_translate("CrossCore", "User Profiles", None))
        self.label_4.setText(_translate("CrossCore", "System Profiles", None))
        self.AddProfile.setText(_translate("CrossCore", "Add Custom Profile", None))
        self.label_5.setText(_translate("CrossCore", "File to Open:", None))
        self.open.setText(_translate("CrossCore", "open", None))
        self.label_9.setText(_translate("CrossCore", "Profile Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("CrossCore", "Settings and Profiles", None))
        self.toolBar.setWindowTitle(_translate("CrossCore", "toolBar", None))

