# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Correlation2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CrossCore(object):
    def setupUi(self, CrossCore):
        CrossCore.setObjectName(_fromUtf8("CrossCore"))
        CrossCore.resize(904, 707)
        self.CrossCore_2 = QtGui.QWidget(CrossCore)
        self.CrossCore_2.setObjectName(_fromUtf8("CrossCore_2"))
        self.gridLayout = QtGui.QGridLayout(self.CrossCore_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.CrossCore_2)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.MainTab = QtGui.QWidget()
        self.MainTab.setObjectName(_fromUtf8("MainTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.MainTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 2, 1)
        self.ShiftSize = QtGui.QSpinBox(self.MainTab)
        self.ShiftSize.setMinimum(50)
        self.ShiftSize.setMaximum(500)
        self.ShiftSize.setSingleStep(2)
        self.ShiftSize.setProperty("value", 102)
        self.ShiftSize.setObjectName(_fromUtf8("ShiftSize"))
        self.gridLayout_2.addWidget(self.ShiftSize, 9, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.MainTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.MainTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.MainTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 9, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.MainTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 2)
        self.correlate = QtGui.QPushButton(self.MainTab)
        self.correlate.setObjectName(_fromUtf8("correlate"))
        self.gridLayout_2.addWidget(self.correlate, 9, 5, 1, 2)
        self.FileBox = QtGui.QListWidget(self.MainTab)
        self.FileBox.setObjectName(_fromUtf8("FileBox"))
        self.gridLayout_2.addWidget(self.FileBox, 1, 4, 6, 3)
        self.listpath = QtGui.QLineEdit(self.MainTab)
        self.listpath.setObjectName(_fromUtf8("listpath"))
        self.gridLayout_2.addWidget(self.listpath, 2, 0, 1, 4)
        self.multiplotshow = QtGui.QCheckBox(self.MainTab)
        self.multiplotshow.setObjectName(_fromUtf8("multiplotshow"))
        self.gridLayout_2.addWidget(self.multiplotshow, 9, 4, 1, 1)
        self.ynlist = QtGui.QCheckBox(self.MainTab)
        self.ynlist.setObjectName(_fromUtf8("ynlist"))
        self.gridLayout_2.addWidget(self.ynlist, 0, 0, 2, 1)
        self.fitdegree = QtGui.QSpinBox(self.MainTab)
        self.fitdegree.setMinimum(1)
        self.fitdegree.setProperty("value", 4)
        self.fitdegree.setObjectName(_fromUtf8("fitdegree"))
        self.gridLayout_2.addWidget(self.fitdegree, 9, 3, 1, 1)
        self.tempfilename = QtGui.QLineEdit(self.MainTab)
        self.tempfilename.setObjectName(_fromUtf8("tempfilename"))
        self.gridLayout_2.addWidget(self.tempfilename, 4, 0, 1, 4)
        self.targetfilename = QtGui.QLineEdit(self.MainTab)
        self.targetfilename.setObjectName(_fromUtf8("targetfilename"))
        self.gridLayout_2.addWidget(self.targetfilename, 6, 0, 2, 4)
        self.infobox = QtGui.QTextBrowser(self.MainTab)
        self.infobox.setObjectName(_fromUtf8("infobox"))
        self.gridLayout_2.addWidget(self.infobox, 10, 0, 1, 7)
        self.tabWidget.addTab(self.MainTab, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_3 = QtGui.QGridLayout(self.settings)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.SaveProfile = QtGui.QPushButton(self.settings)
        self.SaveProfile.setObjectName(_fromUtf8("SaveProfile"))
        self.gridLayout_3.addWidget(self.SaveProfile, 14, 0, 1, 5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reset = QtGui.QPushButton(self.settings)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.horizontalLayout_3.addWidget(self.reset)
        self.save = QtGui.QPushButton(self.settings)
        self.save.setObjectName(_fromUtf8("save"))
        self.horizontalLayout_3.addWidget(self.save)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 5, 2, 3)
        self.ProfileName = QtGui.QLineEdit(self.settings)
        self.ProfileName.setObjectName(_fromUtf8("ProfileName"))
        self.gridLayout_3.addWidget(self.ProfileName, 8, 0, 1, 2)
        self.UserProfile = QtGui.QComboBox(self.settings)
        self.UserProfile.setObjectName(_fromUtf8("UserProfile"))
        self.gridLayout_3.addWidget(self.UserProfile, 3, 0, 1, 2)
        self.useUser = QtGui.QCheckBox(self.settings)
        self.useUser.setObjectName(_fromUtf8("useUser"))
        self.gridLayout_3.addWidget(self.useUser, 4, 0, 2, 2)
        self.listoforders = QtGui.QListWidget(self.settings)
        self.listoforders.setObjectName(_fromUtf8("listoforders"))
        self.gridLayout_3.addWidget(self.listoforders, 9, 0, 5, 1)
        self.uppertext = QtGui.QLineEdit(self.settings)
        self.uppertext.setObjectName(_fromUtf8("uppertext"))
        self.gridLayout_3.addWidget(self.uppertext, 9, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.settings)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 7, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.settings)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.SaveProfile_2 = QtGui.QPushButton(self.settings)
        self.SaveProfile_2.setObjectName(_fromUtf8("SaveProfile_2"))
        self.gridLayout_3.addWidget(self.SaveProfile_2, 13, 1, 1, 1)
        self.Lowertext = QtGui.QLineEdit(self.settings)
        self.Lowertext.setObjectName(_fromUtf8("Lowertext"))
        self.gridLayout_3.addWidget(self.Lowertext, 11, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.settings)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 5, 6, 1, 1)
        self.line = QtGui.QFrame(self.settings)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 3, 14, 3)
        self.SystemProfiles = QtGui.QComboBox(self.settings)
        self.SystemProfiles.setObjectName(_fromUtf8("SystemProfiles"))
        self.gridLayout_3.addWidget(self.SystemProfiles, 1, 0, 1, 2)
        self.open = QtGui.QPushButton(self.settings)
        self.open.setObjectName(_fromUtf8("open"))
        self.gridLayout_3.addWidget(self.open, 5, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.settings)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.label = QtGui.QLabel(self.settings)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 10, 1, 1, 1)
        self.AddProfile = QtGui.QPushButton(self.settings)
        self.AddProfile.setObjectName(_fromUtf8("AddProfile"))
        self.gridLayout_3.addWidget(self.AddProfile, 6, 0, 1, 2)
        self.addout = QtGui.QPushButton(self.settings)
        self.addout.setFlat(False)
        self.addout.setObjectName(_fromUtf8("addout"))
        self.gridLayout_3.addWidget(self.addout, 12, 1, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.settings)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 8, 6, 7, 2)
        self.label_5 = QtGui.QLabel(self.settings)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 6, 1, 1)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.CrossCore_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Return = QtGui.QPushButton(self.widget)
        self.Return.setObjectName(_fromUtf8("Return"))
        self.gridLayout_4.addWidget(self.Return, 0, 0, 1, 1)
        self.Quit = QtGui.QPushButton(self.widget)
        self.Quit.setObjectName(_fromUtf8("Quit"))
        self.gridLayout_4.addWidget(self.Quit, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        CrossCore.setCentralWidget(self.CrossCore_2)
        self.menubar = QtGui.QMenuBar(CrossCore)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuWindpw = QtGui.QMenu(self.menubar)
        self.menuWindpw.setObjectName(_fromUtf8("menuWindpw"))
        CrossCore.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CrossCore)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CrossCore.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(CrossCore)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        CrossCore.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(CrossCore)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionQuit_Program = QtGui.QAction(CrossCore)
        self.actionQuit_Program.setObjectName(_fromUtf8("actionQuit_Program"))
        self.actionPrint = QtGui.QAction(CrossCore)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionSave = QtGui.QAction(CrossCore)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionNope = QtGui.QAction(CrossCore)
        self.actionNope.setObjectName(_fromUtf8("actionNope"))
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionQuit_Program)
        self.menuEdit.addAction(self.actionPrint)
        self.menuEdit.addAction(self.actionSave)
        self.menuWindpw.addAction(self.actionNope)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindpw.menuAction())

        self.retranslateUi(CrossCore)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CrossCore)

    def retranslateUi(self, CrossCore):
        CrossCore.setWindowTitle(_translate("CrossCore", "MainWindow", None))
        self.label_10.setText(_translate("CrossCore", "Shift Size ->", None))
        self.label_8.setText(_translate("CrossCore", "Path To Target file", None))
        self.label_11.setText(_translate("CrossCore", "Files", None))
        self.label_6.setText(_translate("CrossCore", "Degree->", None))
        self.label_7.setText(_translate("CrossCore", "Path To Template file", None))
        self.correlate.setText(_translate("CrossCore", "Correlate", None))
        self.multiplotshow.setText(_translate("CrossCore", "Show All Plots", None))
        self.ynlist.setText(_translate("CrossCore", "Use List?", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("CrossCore", "Main", None))
        self.SaveProfile.setText(_translate("CrossCore", "Save", None))
        self.reset.setText(_translate("CrossCore", "Reset Text", None))
        self.save.setText(_translate("CrossCore", "Commit Changes", None))
        self.useUser.setText(_translate("CrossCore", "Use User Profile", None))
        self.label_9.setText(_translate("CrossCore", "Profile Name", None))
        self.label_3.setText(_translate("CrossCore", "User Profiles", None))
        self.SaveProfile_2.setText(_translate("CrossCore", "Delete", None))
        self.open.setText(_translate("CrossCore", "open", None))
        self.label_4.setText(_translate("CrossCore", "System Profiles", None))
        self.label.setText(_translate("CrossCore", "Upper\n"
"Lower", None))
        self.AddProfile.setText(_translate("CrossCore", "Add Custom Profile", None))
        self.addout.setText(_translate("CrossCore", "Add ignore range", None))
        self.label_5.setText(_translate("CrossCore", "File to Open:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("CrossCore", "Settings and Profiles", None))
        self.Return.setText(_translate("CrossCore", "Return", None))
        self.Quit.setText(_translate("CrossCore", "Quit", None))
        self.menuFile.setTitle(_translate("CrossCore", "File", None))
        self.menuEdit.setTitle(_translate("CrossCore", "Edit", None))
        self.menuWindpw.setTitle(_translate("CrossCore", "Windpw", None))
        self.toolBar.setWindowTitle(_translate("CrossCore", "toolBar", None))
        self.actionQuit.setText(_translate("CrossCore", "Return", None))
        self.actionQuit_Program.setText(_translate("CrossCore", "Quit Program", None))
        self.actionPrint.setText(_translate("CrossCore", "Print", None))
        self.actionSave.setText(_translate("CrossCore", "Save", None))
        self.actionNope.setText(_translate("CrossCore", "Nope", None))

