# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultiplotViewerTesttwo.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MultiplotViewer(object):
    def setupUi(self, MultiplotViewer):
        MultiplotViewer.setObjectName(_fromUtf8("MultiplotViewer"))
        MultiplotViewer.resize(1155, 889)
        self.centralWidget = QtGui.QWidget(MultiplotViewer)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Toolbar = QtGui.QFrame(self.centralWidget)
        self.Toolbar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.Toolbar.setObjectName(_fromUtf8("Toolbar"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Toolbar)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Tabs = QtGui.QTabWidget(self.Toolbar)
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.OnetoTwelve = QtGui.QWidget()
        self.OnetoTwelve.setObjectName(_fromUtf8("OnetoTwelve"))
        self.gridLayout_4 = QtGui.QGridLayout(self.OnetoTwelve)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_2 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_4.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget_6 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.gridLayout_4.addWidget(self.widget_6, 8, 1, 1, 1)
        self.widget_5 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_4.addWidget(self.widget_5, 2, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_4.addWidget(self.widget_3, 8, 0, 1, 1)
        self.widget_8 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_4.addWidget(self.widget_8, 2, 2, 1, 1)
        self.widget_7 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.gridLayout_4.addWidget(self.widget_7, 0, 2, 1, 1)
        self.widget_4 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_4.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_9 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.gridLayout_4.addWidget(self.widget_9, 8, 2, 1, 1)
        self.widget_1 = QtGui.QWidget(self.OnetoTwelve)
        self.widget_1.setObjectName(_fromUtf8("widget_1"))
        self.gridLayout_4.addWidget(self.widget_1, 0, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.checkBox_1 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridLayout_4.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_4.addWidget(self.checkBox_3, 9, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_4.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_4.addWidget(self.checkBox_5, 3, 1, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_4.addWidget(self.checkBox_6, 9, 1, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_4.addWidget(self.checkBox_7, 1, 2, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_4.addWidget(self.checkBox_8, 3, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.OnetoTwelve)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_4.addWidget(self.checkBox_9, 9, 2, 1, 1)
        self.Tabs.addTab(self.OnetoTwelve, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_15 = QtGui.QWidget(self.tab)
        self.widget_15.setObjectName(_fromUtf8("widget_15"))
        self.gridLayout.addWidget(self.widget_15, 9, 4, 1, 1)
        self.widget_16 = QtGui.QWidget(self.tab)
        self.widget_16.setObjectName(_fromUtf8("widget_16"))
        self.gridLayout.addWidget(self.widget_16, 5, 5, 1, 1)
        self.widget_17 = QtGui.QWidget(self.tab)
        self.widget_17.setObjectName(_fromUtf8("widget_17"))
        self.gridLayout.addWidget(self.widget_17, 7, 5, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.tab)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 6, 3, 1, 1)
        self.widget_12 = QtGui.QWidget(self.tab)
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.gridLayout.addWidget(self.widget_12, 9, 3, 1, 1)
        self.widget_10 = QtGui.QWidget(self.tab)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.gridLayout.addWidget(self.widget_10, 5, 3, 1, 1)
        self.widget_13 = QtGui.QWidget(self.tab)
        self.widget_13.setObjectName(_fromUtf8("widget_13"))
        self.gridLayout.addWidget(self.widget_13, 5, 4, 1, 1)
        self.widget_14 = QtGui.QWidget(self.tab)
        self.widget_14.setObjectName(_fromUtf8("widget_14"))
        self.gridLayout.addWidget(self.widget_14, 7, 4, 1, 1)
        self.widget_11 = QtGui.QWidget(self.tab)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.gridLayout.addWidget(self.widget_11, 7, 3, 1, 1)
        self.widget_18 = QtGui.QWidget(self.tab)
        self.widget_18.setObjectName(_fromUtf8("widget_18"))
        self.gridLayout.addWidget(self.widget_18, 9, 5, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.tab)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 8, 3, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.tab)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 10, 3, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.tab)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 6, 4, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.tab)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout.addWidget(self.checkBox_14, 8, 4, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.tab)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout.addWidget(self.checkBox_15, 10, 4, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.tab)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout.addWidget(self.checkBox_16, 6, 5, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.tab)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout.addWidget(self.checkBox_17, 8, 5, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.tab)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout.addWidget(self.checkBox_18, 10, 5, 1, 1)
        self.Tabs.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.widget_24 = QtGui.QWidget(self.tab_2)
        self.widget_24.setObjectName(_fromUtf8("widget_24"))
        self.gridLayout_5.addWidget(self.widget_24, 9, 4, 1, 1)
        self.widget_26 = QtGui.QWidget(self.tab_2)
        self.widget_26.setObjectName(_fromUtf8("widget_26"))
        self.gridLayout_5.addWidget(self.widget_26, 7, 5, 1, 1)
        self.widget_25 = QtGui.QWidget(self.tab_2)
        self.widget_25.setObjectName(_fromUtf8("widget_25"))
        self.gridLayout_5.addWidget(self.widget_25, 5, 5, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_5.addWidget(self.checkBox_20, 8, 3, 1, 1)
        self.widget_20 = QtGui.QWidget(self.tab_2)
        self.widget_20.setObjectName(_fromUtf8("widget_20"))
        self.gridLayout_5.addWidget(self.widget_20, 7, 3, 1, 1)
        self.widget_21 = QtGui.QWidget(self.tab_2)
        self.widget_21.setObjectName(_fromUtf8("widget_21"))
        self.gridLayout_5.addWidget(self.widget_21, 9, 3, 1, 1)
        self.widget_19 = QtGui.QWidget(self.tab_2)
        self.widget_19.setObjectName(_fromUtf8("widget_19"))
        self.gridLayout_5.addWidget(self.widget_19, 5, 3, 1, 1)
        self.widget_23 = QtGui.QWidget(self.tab_2)
        self.widget_23.setObjectName(_fromUtf8("widget_23"))
        self.gridLayout_5.addWidget(self.widget_23, 7, 4, 1, 1)
        self.widget_27 = QtGui.QWidget(self.tab_2)
        self.widget_27.setObjectName(_fromUtf8("widget_27"))
        self.gridLayout_5.addWidget(self.widget_27, 9, 5, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout_5.addWidget(self.checkBox_19, 6, 3, 1, 1)
        self.widget_22 = QtGui.QWidget(self.tab_2)
        self.widget_22.setObjectName(_fromUtf8("widget_22"))
        self.gridLayout_5.addWidget(self.widget_22, 5, 4, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout_5.addWidget(self.checkBox_21, 10, 3, 1, 1)
        self.checkBox_22 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout_5.addWidget(self.checkBox_22, 6, 4, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout_5.addWidget(self.checkBox_23, 8, 4, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridLayout_5.addWidget(self.checkBox_24, 10, 4, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout_5.addWidget(self.checkBox_25, 6, 5, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridLayout_5.addWidget(self.checkBox_26, 8, 5, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_27.setChecked(True)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridLayout_5.addWidget(self.checkBox_27, 10, 5, 1, 1)
        self.Tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setMargin(11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.widget_36 = QtGui.QWidget(self.tab_3)
        self.widget_36.setObjectName(_fromUtf8("widget_36"))
        self.gridLayout_6.addWidget(self.widget_36, 4, 2, 1, 1)
        self.checkBox_29 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_29.setChecked(True)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.gridLayout_6.addWidget(self.checkBox_29, 3, 0, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.gridLayout_6.addWidget(self.checkBox_28, 1, 0, 1, 1)
        self.widget_30 = QtGui.QWidget(self.tab_3)
        self.widget_30.setObjectName(_fromUtf8("widget_30"))
        self.gridLayout_6.addWidget(self.widget_30, 4, 0, 1, 1)
        self.widget_29 = QtGui.QWidget(self.tab_3)
        self.widget_29.setObjectName(_fromUtf8("widget_29"))
        self.gridLayout_6.addWidget(self.widget_29, 2, 0, 1, 1)
        self.widget_34 = QtGui.QWidget(self.tab_3)
        self.widget_34.setObjectName(_fromUtf8("widget_34"))
        self.gridLayout_6.addWidget(self.widget_34, 0, 2, 1, 1)
        self.widget_28 = QtGui.QWidget(self.tab_3)
        self.widget_28.setObjectName(_fromUtf8("widget_28"))
        self.gridLayout_6.addWidget(self.widget_28, 0, 0, 1, 1)
        self.widget_33 = QtGui.QWidget(self.tab_3)
        self.widget_33.setObjectName(_fromUtf8("widget_33"))
        self.gridLayout_6.addWidget(self.widget_33, 4, 1, 1, 1)
        self.widget_35 = QtGui.QWidget(self.tab_3)
        self.widget_35.setObjectName(_fromUtf8("widget_35"))
        self.gridLayout_6.addWidget(self.widget_35, 2, 2, 1, 1)
        self.widget_32 = QtGui.QWidget(self.tab_3)
        self.widget_32.setObjectName(_fromUtf8("widget_32"))
        self.gridLayout_6.addWidget(self.widget_32, 2, 1, 1, 1)
        self.widget_31 = QtGui.QWidget(self.tab_3)
        self.widget_31.setObjectName(_fromUtf8("widget_31"))
        self.gridLayout_6.addWidget(self.widget_31, 0, 1, 1, 1)
        self.checkBox_30 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_30.setChecked(True)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.gridLayout_6.addWidget(self.checkBox_30, 5, 0, 1, 1)
        self.checkBox_31 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_31.setChecked(True)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.gridLayout_6.addWidget(self.checkBox_31, 1, 1, 1, 1)
        self.checkBox_32 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_32.setChecked(True)
        self.checkBox_32.setObjectName(_fromUtf8("checkBox_32"))
        self.gridLayout_6.addWidget(self.checkBox_32, 3, 1, 1, 1)
        self.checkBox_33 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_33.setChecked(True)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.gridLayout_6.addWidget(self.checkBox_33, 5, 1, 1, 1)
        self.checkBox_34 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_34.setChecked(True)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.gridLayout_6.addWidget(self.checkBox_34, 1, 2, 1, 1)
        self.checkBox_35 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_35.setChecked(True)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.gridLayout_6.addWidget(self.checkBox_35, 3, 2, 1, 1)
        self.checkBox_36 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_36.setChecked(True)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.gridLayout_6.addWidget(self.checkBox_36, 5, 2, 1, 1)
        self.Tabs.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_7.setMargin(11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.widget_43 = QtGui.QWidget(self.tab_4)
        self.widget_43.setObjectName(_fromUtf8("widget_43"))
        self.gridLayout_7.addWidget(self.widget_43, 0, 2, 1, 1)
        self.widget_40 = QtGui.QWidget(self.tab_4)
        self.widget_40.setObjectName(_fromUtf8("widget_40"))
        self.gridLayout_7.addWidget(self.widget_40, 0, 1, 1, 1)
        self.widget_44 = QtGui.QWidget(self.tab_4)
        self.widget_44.setObjectName(_fromUtf8("widget_44"))
        self.gridLayout_7.addWidget(self.widget_44, 2, 2, 1, 1)
        self.widget_45 = QtGui.QWidget(self.tab_4)
        self.widget_45.setObjectName(_fromUtf8("widget_45"))
        self.gridLayout_7.addWidget(self.widget_45, 4, 2, 1, 1)
        self.checkBox_37 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_37.setChecked(True)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.gridLayout_7.addWidget(self.checkBox_37, 1, 0, 1, 1)
        self.checkBox_38 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_38.setChecked(True)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.gridLayout_7.addWidget(self.checkBox_38, 3, 0, 1, 1)
        self.widget_41 = QtGui.QWidget(self.tab_4)
        self.widget_41.setObjectName(_fromUtf8("widget_41"))
        self.gridLayout_7.addWidget(self.widget_41, 2, 1, 1, 1)
        self.widget_37 = QtGui.QWidget(self.tab_4)
        self.widget_37.setObjectName(_fromUtf8("widget_37"))
        self.gridLayout_7.addWidget(self.widget_37, 0, 0, 1, 1)
        self.widget_38 = QtGui.QWidget(self.tab_4)
        self.widget_38.setObjectName(_fromUtf8("widget_38"))
        self.gridLayout_7.addWidget(self.widget_38, 2, 0, 1, 1)
        self.widget_42 = QtGui.QWidget(self.tab_4)
        self.widget_42.setObjectName(_fromUtf8("widget_42"))
        self.gridLayout_7.addWidget(self.widget_42, 4, 1, 1, 1)
        self.widget_39 = QtGui.QWidget(self.tab_4)
        self.widget_39.setObjectName(_fromUtf8("widget_39"))
        self.gridLayout_7.addWidget(self.widget_39, 4, 0, 1, 1)
        self.checkBox_39 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_39.setChecked(True)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.gridLayout_7.addWidget(self.checkBox_39, 5, 0, 1, 1)
        self.checkBox_40 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_40.setChecked(True)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.gridLayout_7.addWidget(self.checkBox_40, 1, 1, 1, 1)
        self.checkBox_41 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_41.setChecked(True)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.gridLayout_7.addWidget(self.checkBox_41, 3, 1, 1, 1)
        self.checkBox_42 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_42.setChecked(True)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.gridLayout_7.addWidget(self.checkBox_42, 5, 1, 1, 1)
        self.checkBox_43 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_43.setChecked(True)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.gridLayout_7.addWidget(self.checkBox_43, 1, 2, 1, 1)
        self.checkBox_44 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_44.setChecked(True)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.gridLayout_7.addWidget(self.checkBox_44, 3, 2, 1, 1)
        self.checkBox_45 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_45.setChecked(True)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.gridLayout_7.addWidget(self.checkBox_45, 5, 2, 1, 1)
        self.Tabs.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_8.setMargin(11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.widget_49 = QtGui.QWidget(self.tab_5)
        self.widget_49.setObjectName(_fromUtf8("widget_49"))
        self.gridLayout_8.addWidget(self.widget_49, 0, 1, 1, 1)
        self.widget_46 = QtGui.QWidget(self.tab_5)
        self.widget_46.setObjectName(_fromUtf8("widget_46"))
        self.gridLayout_8.addWidget(self.widget_46, 0, 0, 1, 1)
        self.widget_52 = QtGui.QWidget(self.tab_5)
        self.widget_52.setObjectName(_fromUtf8("widget_52"))
        self.gridLayout_8.addWidget(self.widget_52, 0, 2, 1, 1)
        self.widget_48 = QtGui.QWidget(self.tab_5)
        self.widget_48.setObjectName(_fromUtf8("widget_48"))
        self.gridLayout_8.addWidget(self.widget_48, 4, 0, 1, 1)
        self.checkBox_46 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_46.setChecked(True)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.gridLayout_8.addWidget(self.checkBox_46, 1, 0, 1, 1)
        self.checkBox_47 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_47.setChecked(True)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.gridLayout_8.addWidget(self.checkBox_47, 3, 0, 1, 1)
        self.widget_50 = QtGui.QWidget(self.tab_5)
        self.widget_50.setObjectName(_fromUtf8("widget_50"))
        self.gridLayout_8.addWidget(self.widget_50, 2, 1, 1, 1)
        self.widget_47 = QtGui.QWidget(self.tab_5)
        self.widget_47.setObjectName(_fromUtf8("widget_47"))
        self.gridLayout_8.addWidget(self.widget_47, 2, 0, 1, 1)
        self.widget_51 = QtGui.QWidget(self.tab_5)
        self.widget_51.setObjectName(_fromUtf8("widget_51"))
        self.gridLayout_8.addWidget(self.widget_51, 4, 1, 1, 1)
        self.widget_54 = QtGui.QWidget(self.tab_5)
        self.widget_54.setObjectName(_fromUtf8("widget_54"))
        self.gridLayout_8.addWidget(self.widget_54, 4, 2, 1, 1)
        self.widget_53 = QtGui.QWidget(self.tab_5)
        self.widget_53.setObjectName(_fromUtf8("widget_53"))
        self.gridLayout_8.addWidget(self.widget_53, 2, 2, 1, 1)
        self.checkBox_48 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_48.setChecked(True)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.gridLayout_8.addWidget(self.checkBox_48, 5, 0, 1, 1)
        self.checkBox_49 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_49.setChecked(True)
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.gridLayout_8.addWidget(self.checkBox_49, 1, 1, 1, 1)
        self.checkBox_50 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_50.setChecked(True)
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.gridLayout_8.addWidget(self.checkBox_50, 3, 1, 1, 1)
        self.checkBox_51 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_51.setChecked(True)
        self.checkBox_51.setObjectName(_fromUtf8("checkBox_51"))
        self.gridLayout_8.addWidget(self.checkBox_51, 5, 1, 1, 1)
        self.checkBox_52 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_52.setChecked(True)
        self.checkBox_52.setObjectName(_fromUtf8("checkBox_52"))
        self.gridLayout_8.addWidget(self.checkBox_52, 1, 2, 1, 1)
        self.checkBox_53 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_53.setChecked(True)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.gridLayout_8.addWidget(self.checkBox_53, 3, 2, 1, 1)
        self.checkBox_54 = QtGui.QCheckBox(self.tab_5)
        self.checkBox_54.setChecked(True)
        self.checkBox_54.setObjectName(_fromUtf8("checkBox_54"))
        self.gridLayout_8.addWidget(self.checkBox_54, 5, 2, 1, 1)
        self.Tabs.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_9.setMargin(11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.checkBox_55 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_55.setChecked(True)
        self.checkBox_55.setObjectName(_fromUtf8("checkBox_55"))
        self.gridLayout_9.addWidget(self.checkBox_55, 1, 0, 1, 1)
        self.widget_62 = QtGui.QWidget(self.tab_6)
        self.widget_62.setObjectName(_fromUtf8("widget_62"))
        self.gridLayout_9.addWidget(self.widget_62, 2, 2, 1, 1)
        self.widget_57 = QtGui.QWidget(self.tab_6)
        self.widget_57.setObjectName(_fromUtf8("widget_57"))
        self.gridLayout_9.addWidget(self.widget_57, 4, 0, 1, 1)
        self.widget_55 = QtGui.QWidget(self.tab_6)
        self.widget_55.setObjectName(_fromUtf8("widget_55"))
        self.gridLayout_9.addWidget(self.widget_55, 0, 0, 1, 1)
        self.checkBox_56 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_56.setChecked(True)
        self.checkBox_56.setObjectName(_fromUtf8("checkBox_56"))
        self.gridLayout_9.addWidget(self.checkBox_56, 3, 0, 1, 1)
        self.widget_61 = QtGui.QWidget(self.tab_6)
        self.widget_61.setObjectName(_fromUtf8("widget_61"))
        self.gridLayout_9.addWidget(self.widget_61, 0, 2, 1, 1)
        self.widget_58 = QtGui.QWidget(self.tab_6)
        self.widget_58.setObjectName(_fromUtf8("widget_58"))
        self.gridLayout_9.addWidget(self.widget_58, 0, 1, 1, 1)
        self.widget_56 = QtGui.QWidget(self.tab_6)
        self.widget_56.setObjectName(_fromUtf8("widget_56"))
        self.gridLayout_9.addWidget(self.widget_56, 2, 0, 1, 1)
        self.widget_59 = QtGui.QWidget(self.tab_6)
        self.widget_59.setObjectName(_fromUtf8("widget_59"))
        self.gridLayout_9.addWidget(self.widget_59, 2, 1, 1, 1)
        self.widget_60 = QtGui.QWidget(self.tab_6)
        self.widget_60.setObjectName(_fromUtf8("widget_60"))
        self.gridLayout_9.addWidget(self.widget_60, 4, 1, 1, 1)
        self.checkBox_57 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_57.setChecked(True)
        self.checkBox_57.setObjectName(_fromUtf8("checkBox_57"))
        self.gridLayout_9.addWidget(self.checkBox_57, 5, 0, 1, 1)
        self.checkBox_58 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_58.setChecked(True)
        self.checkBox_58.setObjectName(_fromUtf8("checkBox_58"))
        self.gridLayout_9.addWidget(self.checkBox_58, 1, 1, 1, 1)
        self.checkBox_59 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_59.setChecked(True)
        self.checkBox_59.setObjectName(_fromUtf8("checkBox_59"))
        self.gridLayout_9.addWidget(self.checkBox_59, 3, 1, 1, 1)
        self.checkBox_60 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_60.setChecked(True)
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.gridLayout_9.addWidget(self.checkBox_60, 5, 1, 1, 1)
        self.checkBox_61 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_61.setChecked(True)
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.gridLayout_9.addWidget(self.checkBox_61, 1, 2, 1, 1)
        self.checkBox_62 = QtGui.QCheckBox(self.tab_6)
        self.checkBox_62.setChecked(True)
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.gridLayout_9.addWidget(self.checkBox_62, 3, 2, 1, 1)
        self.Tabs.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.Tabs, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(self.Toolbar)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget)
        self.gridLayout_10.setMargin(11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Advance = QtGui.QPushButton(self.widget)
        self.Advance.setObjectName(_fromUtf8("Advance"))
        self.gridLayout_10.addWidget(self.Advance, 0, 0, 1, 1)
        self.ForceAdvance = QtGui.QPushButton(self.widget)
        self.ForceAdvance.setObjectName(_fromUtf8("ForceAdvance"))
        self.gridLayout_10.addWidget(self.ForceAdvance, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Toolbar, 0, 1, 1, 1)
        MultiplotViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MultiplotViewer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1155, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuVersuib_IObe = QtGui.QMenu(self.menuBar)
        self.menuVersuib_IObe.setObjectName(_fromUtf8("menuVersuib_IObe"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuWindow = QtGui.QMenu(self.menuBar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        MultiplotViewer.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MultiplotViewer)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MultiplotViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MultiplotViewer)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MultiplotViewer.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MultiplotViewer)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSave_all_plots = QtGui.QAction(MultiplotViewer)
        self.actionSave_all_plots.setObjectName(_fromUtf8("actionSave_all_plots"))
        self.menuVersuib_IObe.addAction(self.actionQuit)
        self.menuVersuib_IObe.addAction(self.actionSave_all_plots)
        self.menuBar.addAction(self.menuVersuib_IObe.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MultiplotViewer)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MultiplotViewer)

    def retranslateUi(self, MultiplotViewer):
        MultiplotViewer.setWindowTitle(_translate("MultiplotViewer", "TestWindow", None))
        self.checkBox_2.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_1.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_3.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_4.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_5.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_6.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_7.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_8.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_9.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.OnetoTwelve), _translate("MultiplotViewer", "1-9", None))
        self.checkBox_10.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_11.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_12.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_13.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_14.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_15.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_16.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_17.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_18.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MultiplotViewer", "10-18", None))
        self.checkBox_20.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_19.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_21.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_22.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_23.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_24.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_25.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_26.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_27.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MultiplotViewer", "19-27", None))
        self.checkBox_29.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_28.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_30.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_31.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_32.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_33.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_34.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_35.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_36.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), _translate("MultiplotViewer", "28-36", None))
        self.checkBox_37.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_38.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_39.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_40.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_41.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_42.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_43.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_44.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_45.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), _translate("MultiplotViewer", "37-45", None))
        self.checkBox_46.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_47.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_48.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_49.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_50.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_51.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_52.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_53.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_54.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_5), _translate("MultiplotViewer", "46-54", None))
        self.checkBox_55.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_56.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_57.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_58.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_59.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_60.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_61.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.checkBox_62.setText(_translate("MultiplotViewer", "CheckBox", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_6), _translate("MultiplotViewer", "55-62", None))
        self.Advance.setText(_translate("MultiplotViewer", "Advance", None))
        self.ForceAdvance.setToolTip(_translate("MultiplotViewer", "Will Not fit any data but will rather enter the string \'UNABLE TO FIT\' in the output file", None))
        self.ForceAdvance.setText(_translate("MultiplotViewer", "Force Advance", None))
        self.menuVersuib_IObe.setTitle(_translate("MultiplotViewer", "File", None))
        self.menuEdit.setTitle(_translate("MultiplotViewer", "Edit", None))
        self.menuWindow.setTitle(_translate("MultiplotViewer", "Window", None))
        self.actionQuit.setText(_translate("MultiplotViewer", "Quit", None))
        self.actionSave_all_plots.setText(_translate("MultiplotViewer", "Save all plots", None))

