# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orbitalfitter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OrbitalFitter(object):
    def setupUi(self, OrbitalFitter):
        OrbitalFitter.setObjectName(_fromUtf8("OrbitalFitter"))
        OrbitalFitter.resize(691, 908)
        self.centralWidget = QtGui.QWidget(OrbitalFitter)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_2 = QtGui.QWidget(self.centralWidget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.SettingsWindow = QtGui.QWidget(self.widget_2)
        self.SettingsWindow.setObjectName(_fromUtf8("SettingsWindow"))
        self.gridLayout_3 = QtGui.QGridLayout(self.SettingsWindow)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.KnownPeriod = QtGui.QCheckBox(self.SettingsWindow)
        self.KnownPeriod.setChecked(True)
        self.KnownPeriod.setObjectName(_fromUtf8("KnownPeriod"))
        self.gridLayout_3.addWidget(self.KnownPeriod, 4, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.SettingsWindow)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.Period = QtGui.QLineEdit(self.SettingsWindow)
        self.Period.setToolTip(_fromUtf8(""))
        self.Period.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferLowercase)
        self.Period.setObjectName(_fromUtf8("Period"))
        self.gridLayout_3.addWidget(self.Period, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.SettingsWindow)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.SettingsWindow)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 5, 0, 1, 1)
        self.ListPath = QtGui.QLineEdit(self.SettingsWindow)
        self.ListPath.setObjectName(_fromUtf8("ListPath"))
        self.gridLayout_3.addWidget(self.ListPath, 5, 1, 1, 1)
        self.Eccentricity = QtGui.QCheckBox(self.SettingsWindow)
        self.Eccentricity.setCheckable(False)
        self.Eccentricity.setChecked(False)
        self.Eccentricity.setObjectName(_fromUtf8("Eccentricity"))
        self.gridLayout_3.addWidget(self.Eccentricity, 1, 2, 1, 1)
        self.EccentricityValue = QtGui.QDoubleSpinBox(self.SettingsWindow)
        self.EccentricityValue.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.EccentricityValue.setMaximum(1.0)
        self.EccentricityValue.setSingleStep(0.05)
        self.EccentricityValue.setObjectName(_fromUtf8("EccentricityValue"))
        self.gridLayout_3.addWidget(self.EccentricityValue, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.SettingsWindow, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 2)
        self.Close = QtGui.QPushButton(self.centralWidget)
        self.Close.setObjectName(_fromUtf8("Close"))
        self.gridLayout.addWidget(self.Close, 4, 0, 1, 1)
        self.Fit = QtGui.QPushButton(self.centralWidget)
        self.Fit.setObjectName(_fromUtf8("Fit"))
        self.gridLayout.addWidget(self.Fit, 1, 0, 1, 2)
        self.Save = QtGui.QPushButton(self.centralWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 134, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Save.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Save.setFont(font)
        self.Save.setObjectName(_fromUtf8("Save"))
        self.gridLayout.addWidget(self.Save, 4, 1, 1, 1)
        self.FitWindow = QtGui.QWidget(self.centralWidget)
        self.FitWindow.setObjectName(_fromUtf8("FitWindow"))
        self.Graph = QtGui.QWidget(self.FitWindow)
        self.Graph.setGeometry(QtCore.QRect(10, 0, 641, 311))
        self.Graph.setObjectName(_fromUtf8("Graph"))
        self.ToolbarMPL = QtGui.QWidget(self.FitWindow)
        self.ToolbarMPL.setGeometry(QtCore.QRect(10, 320, 641, 51))
        self.ToolbarMPL.setObjectName(_fromUtf8("ToolbarMPL"))
        self.gridLayout.addWidget(self.FitWindow, 2, 0, 1, 2)
        OrbitalFitter.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(OrbitalFitter)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 691, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuWindow = QtGui.QMenu(self.menuBar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        OrbitalFitter.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(OrbitalFitter)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        OrbitalFitter.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(OrbitalFitter)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        OrbitalFitter.setStatusBar(self.statusBar)
        self.actionSave = QtGui.QAction(OrbitalFitter)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(OrbitalFitter)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCopy = QtGui.QAction(OrbitalFitter)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(OrbitalFitter)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSize = QtGui.QAction(OrbitalFitter)
        self.actionSize.setObjectName(_fromUtf8("actionSize"))
        self.actionZoom = QtGui.QAction(OrbitalFitter)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionReset = QtGui.QAction(OrbitalFitter)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionNo_Help_Here = QtGui.QAction(OrbitalFitter)
        self.actionNo_Help_Here.setObjectName(_fromUtf8("actionNo_Help_Here"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuWindow.addAction(self.actionSize)
        self.menuWindow.addAction(self.actionZoom)
        self.menuWindow.addAction(self.actionReset)
        self.menuHelp.addAction(self.actionNo_Help_Here)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(OrbitalFitter)
        QtCore.QMetaObject.connectSlotsByName(OrbitalFitter)

    def retranslateUi(self, OrbitalFitter):
        OrbitalFitter.setWindowTitle(_translate("OrbitalFitter", "OrbitalFitter", None))
        self.KnownPeriod.setText(_translate("OrbitalFitter", "Period is known?", None))
        self.label_2.setText(_translate("OrbitalFitter", "Enter Period:", None))
        self.label_3.setText(_translate("OrbitalFitter", "Eccentricity", None))
        self.label.setText(_translate("OrbitalFitter", "Enter List Path Name:", None))
        self.Eccentricity.setText(_translate("OrbitalFitter", "Eccentricity", None))
        self.Close.setText(_translate("OrbitalFitter", "Close", None))
        self.Fit.setText(_translate("OrbitalFitter", "Attempt Orbital Soultion Fit", None))
        self.Save.setText(_translate("OrbitalFitter", "Save", None))
        self.menuFile.setTitle(_translate("OrbitalFitter", "File", None))
        self.menuEdit.setTitle(_translate("OrbitalFitter", "Edit", None))
        self.menuWindow.setTitle(_translate("OrbitalFitter", "Window", None))
        self.menuHelp.setTitle(_translate("OrbitalFitter", "Help", None))
        self.actionSave.setText(_translate("OrbitalFitter", "Save", None))
        self.actionQuit.setText(_translate("OrbitalFitter", "Quit", None))
        self.actionCopy.setText(_translate("OrbitalFitter", "Copy", None))
        self.actionPaste.setText(_translate("OrbitalFitter", "Paste", None))
        self.actionSize.setText(_translate("OrbitalFitter", "Size", None))
        self.actionZoom.setText(_translate("OrbitalFitter", "Zoom", None))
        self.actionReset.setText(_translate("OrbitalFitter", "Reset", None))
        self.actionNo_Help_Here.setText(_translate("OrbitalFitter", "No Help Here", None))

