# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SAULGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SAUL(object):
    def setupUi(self, SAUL):
        SAUL.setObjectName(_fromUtf8("SAUL"))
        SAUL.resize(1674, 1107)
        self.Main = QtGui.QWidget(SAUL)
        self.Main.setObjectName(_fromUtf8("Main"))
        self.gridLayout = QtGui.QGridLayout(self.Main)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PlotViewer = QtGui.QWidget(self.Main)
        self.PlotViewer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotViewer.sizePolicy().hasHeightForWidth())
        self.PlotViewer.setSizePolicy(sizePolicy)
        self.PlotViewer.setObjectName(_fromUtf8("PlotViewer"))
        self.gridLayout_4 = QtGui.QGridLayout(self.PlotViewer)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Command = QtGui.QLineEdit(self.PlotViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Command.sizePolicy().hasHeightForWidth())
        self.Command.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        self.Command.setFont(font)
        self.Command.setObjectName(_fromUtf8("Command"))
        self.gridLayout_4.addWidget(self.Command, 2, 1, 1, 1)
        self.Terminal = QtGui.QTextBrowser(self.PlotViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminal.sizePolicy().hasHeightForWidth())
        self.Terminal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        self.Terminal.setFont(font)
        self.Terminal.setObjectName(_fromUtf8("Terminal"))
        self.gridLayout_4.addWidget(self.Terminal, 1, 1, 1, 1)
        self.TerminalLabel = QtGui.QLabel(self.PlotViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TerminalLabel.sizePolicy().hasHeightForWidth())
        self.TerminalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.TerminalLabel.setFont(font)
        self.TerminalLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.TerminalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TerminalLabel.setObjectName(_fromUtf8("TerminalLabel"))
        self.gridLayout_4.addWidget(self.TerminalLabel, 0, 1, 1, 1)
        self.PlotControllabel = QtGui.QLabel(self.PlotViewer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotControllabel.sizePolicy().hasHeightForWidth())
        self.PlotControllabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.PlotControllabel.setFont(font)
        self.PlotControllabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.PlotControllabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PlotControllabel.setObjectName(_fromUtf8("PlotControllabel"))
        self.gridLayout_4.addWidget(self.PlotControllabel, 0, 2, 1, 1)
        self.PlotControls = QtGui.QWidget(self.PlotViewer)
        self.PlotControls.setObjectName(_fromUtf8("PlotControls"))
        self.gridLayout_16 = QtGui.QGridLayout(self.PlotControls)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.PlotTwoShowingLabel = QtGui.QLabel(self.PlotControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotTwoShowingLabel.sizePolicy().hasHeightForWidth())
        self.PlotTwoShowingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(15)
        font.setUnderline(True)
        self.PlotTwoShowingLabel.setFont(font)
        self.PlotTwoShowingLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PlotTwoShowingLabel.setObjectName(_fromUtf8("PlotTwoShowingLabel"))
        self.gridLayout_16.addWidget(self.PlotTwoShowingLabel, 1, 0, 1, 1)
        self.SavePlotTwo = QtGui.QPushButton(self.PlotControls)
        self.SavePlotTwo.setObjectName(_fromUtf8("SavePlotTwo"))
        self.gridLayout_16.addWidget(self.SavePlotTwo, 1, 2, 1, 1)
        self.SavePlotOne = QtGui.QPushButton(self.PlotControls)
        self.SavePlotOne.setObjectName(_fromUtf8("SavePlotOne"))
        self.gridLayout_16.addWidget(self.SavePlotOne, 0, 2, 1, 1)
        self.WhatIsOnPlotOne = QtGui.QLabel(self.PlotControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhatIsOnPlotOne.sizePolicy().hasHeightForWidth())
        self.WhatIsOnPlotOne.setSizePolicy(sizePolicy)
        self.WhatIsOnPlotOne.setObjectName(_fromUtf8("WhatIsOnPlotOne"))
        self.gridLayout_16.addWidget(self.WhatIsOnPlotOne, 0, 1, 1, 1)
        self.JumpToOrder = QtGui.QPushButton(self.PlotControls)
        self.JumpToOrder.setObjectName(_fromUtf8("JumpToOrder"))
        self.gridLayout_16.addWidget(self.JumpToOrder, 4, 1, 1, 1)
        self.WhatIsOnePlotTwo = QtGui.QLabel(self.PlotControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WhatIsOnePlotTwo.sizePolicy().hasHeightForWidth())
        self.WhatIsOnePlotTwo.setSizePolicy(sizePolicy)
        self.WhatIsOnePlotTwo.setObjectName(_fromUtf8("WhatIsOnePlotTwo"))
        self.gridLayout_16.addWidget(self.WhatIsOnePlotTwo, 1, 1, 1, 1)
        self.OrderAdvance = QtGui.QPushButton(self.PlotControls)
        self.OrderAdvance.setObjectName(_fromUtf8("OrderAdvance"))
        self.gridLayout_16.addWidget(self.OrderAdvance, 2, 1, 1, 1)
        self.PlotOneShowingLabel = QtGui.QLabel(self.PlotControls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotOneShowingLabel.sizePolicy().hasHeightForWidth())
        self.PlotOneShowingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(15)
        font.setUnderline(True)
        self.PlotOneShowingLabel.setFont(font)
        self.PlotOneShowingLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PlotOneShowingLabel.setObjectName(_fromUtf8("PlotOneShowingLabel"))
        self.gridLayout_16.addWidget(self.PlotOneShowingLabel, 0, 0, 1, 1)
        self.OrderRetreate = QtGui.QPushButton(self.PlotControls)
        self.OrderRetreate.setObjectName(_fromUtf8("OrderRetreate"))
        self.gridLayout_16.addWidget(self.OrderRetreate, 2, 0, 1, 1)
        self.OrderToGoTo = QtGui.QSpinBox(self.PlotControls)
        self.OrderToGoTo.setMinimum(1)
        self.OrderToGoTo.setMaximum(62)
        self.OrderToGoTo.setObjectName(_fromUtf8("OrderToGoTo"))
        self.gridLayout_16.addWidget(self.OrderToGoTo, 4, 0, 1, 1)
        self.ToggleSpectra = QtGui.QPushButton(self.PlotControls)
        self.ToggleSpectra.setObjectName(_fromUtf8("ToggleSpectra"))
        self.gridLayout_16.addWidget(self.ToggleSpectra, 5, 0, 1, 1)
        self.ReastFit = QtGui.QPushButton(self.PlotControls)
        self.ReastFit.setObjectName(_fromUtf8("ReastFit"))
        self.gridLayout_16.addWidget(self.ReastFit, 5, 1, 1, 1)
        self.RemoveSpectra = QtGui.QPushButton(self.PlotControls)
        self.RemoveSpectra.setObjectName(_fromUtf8("RemoveSpectra"))
        self.gridLayout_16.addWidget(self.RemoveSpectra, 2, 2, 1, 1)
        self.AddSpectra = QtGui.QPushButton(self.PlotControls)
        self.AddSpectra.setObjectName(_fromUtf8("AddSpectra"))
        self.gridLayout_16.addWidget(self.AddSpectra, 4, 2, 1, 1)
        self.ClearPlots = QtGui.QPushButton(self.PlotControls)
        self.ClearPlots.setObjectName(_fromUtf8("ClearPlots"))
        self.gridLayout_16.addWidget(self.ClearPlots, 5, 2, 1, 1)
        self.gridLayout_4.addWidget(self.PlotControls, 1, 2, 2, 1)
        self.gridLayout.addWidget(self.PlotViewer, 2, 0, 1, 2)
        self.GeneralFunctions = QtGui.QWidget(self.Main)
        self.GeneralFunctions.setObjectName(_fromUtf8("GeneralFunctions"))
        self.gridLayout_2 = QtGui.QGridLayout(self.GeneralFunctions)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ChangeDirectory = QtGui.QPushButton(self.GeneralFunctions)
        self.ChangeDirectory.setObjectName(_fromUtf8("ChangeDirectory"))
        self.gridLayout_2.addWidget(self.ChangeDirectory, 1, 0, 1, 2)
        self.GeneratePathFile = QtGui.QPushButton(self.GeneralFunctions)
        self.GeneratePathFile.setObjectName(_fromUtf8("GeneratePathFile"))
        self.gridLayout_2.addWidget(self.GeneratePathFile, 1, 2, 1, 1)
        self.Quit = QtGui.QPushButton(self.GeneralFunctions)
        self.Quit.setObjectName(_fromUtf8("Quit"))
        self.gridLayout_2.addWidget(self.Quit, 2, 2, 1, 1)
        self.Reload = QtGui.QPushButton(self.GeneralFunctions)
        self.Reload.setObjectName(_fromUtf8("Reload"))
        self.gridLayout_2.addWidget(self.Reload, 2, 0, 1, 2)
        self.GF = QtGui.QLabel(self.GeneralFunctions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GF.sizePolicy().hasHeightForWidth())
        self.GF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.GF.setFont(font)
        self.GF.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GF.setAlignment(QtCore.Qt.AlignCenter)
        self.GF.setObjectName(_fromUtf8("GF"))
        self.gridLayout_2.addWidget(self.GF, 0, 0, 1, 3)
        self.widget_3 = QtGui.QWidget(self.GeneralFunctions)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.PathFilesBrowser = QtGui.QListWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathFilesBrowser.sizePolicy().hasHeightForWidth())
        self.PathFilesBrowser.setSizePolicy(sizePolicy)
        self.PathFilesBrowser.setObjectName(_fromUtf8("PathFilesBrowser"))
        self.gridLayout_3.addWidget(self.PathFilesBrowser, 1, 0, 1, 1)
        self.DataPathsLabel = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataPathsLabel.sizePolicy().hasHeightForWidth())
        self.DataPathsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.DataPathsLabel.setFont(font)
        self.DataPathsLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.DataPathsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DataPathsLabel.setObjectName(_fromUtf8("DataPathsLabel"))
        self.gridLayout_3.addWidget(self.DataPathsLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 4, 0, 1, 3)
        self.GeneralInfo = QtGui.QTextBrowser(self.GeneralFunctions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneralInfo.sizePolicy().hasHeightForWidth())
        self.GeneralInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        self.GeneralInfo.setFont(font)
        self.GeneralInfo.setObjectName(_fromUtf8("GeneralInfo"))
        self.gridLayout_2.addWidget(self.GeneralInfo, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.GeneralFunctions, 0, 0, 2, 1)
        self.AdvancedFunctions = QtGui.QWidget(self.Main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdvancedFunctions.sizePolicy().hasHeightForWidth())
        self.AdvancedFunctions.setSizePolicy(sizePolicy)
        self.AdvancedFunctions.setObjectName(_fromUtf8("AdvancedFunctions"))
        self.gridLayout_6 = QtGui.QGridLayout(self.AdvancedFunctions)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Functions = QtGui.QTabWidget(self.AdvancedFunctions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Functions.sizePolicy().hasHeightForWidth())
        self.Functions.setSizePolicy(sizePolicy)
        self.Functions.setObjectName(_fromUtf8("Functions"))
        self.BSP = QtGui.QWidget()
        self.BSP.setObjectName(_fromUtf8("BSP"))
        self.gridLayout_5 = QtGui.QGridLayout(self.BSP)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.line = QtGui.QFrame(self.BSP)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_5.addWidget(self.line, 5, 1, 1, 5)
        self.Normalizeyn = QtGui.QCheckBox(self.BSP)
        self.Normalizeyn.setChecked(True)
        self.Normalizeyn.setObjectName(_fromUtf8("Normalizeyn"))
        self.gridLayout_5.addWidget(self.Normalizeyn, 3, 1, 1, 1)
        self.BSPPath = QtGui.QLineEdit(self.BSP)
        self.BSPPath.setObjectName(_fromUtf8("BSPPath"))
        self.gridLayout_5.addWidget(self.BSPPath, 1, 1, 1, 5)
        self.line_4 = QtGui.QFrame(self.BSP)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 6, 2, 1, 1)
        self.NumToStack = QtGui.QSpinBox(self.BSP)
        self.NumToStack.setObjectName(_fromUtf8("NumToStack"))
        self.gridLayout_5.addWidget(self.NumToStack, 6, 5, 1, 1)
        self.BSPLabel = QtGui.QLabel(self.BSP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSPLabel.sizePolicy().hasHeightForWidth())
        self.BSPLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.BSPLabel.setFont(font)
        self.BSPLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.BSPLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BSPLabel.setObjectName(_fromUtf8("BSPLabel"))
        self.gridLayout_5.addWidget(self.BSPLabel, 0, 1, 1, 5)
        self.StackAll = QtGui.QCheckBox(self.BSP)
        self.StackAll.setObjectName(_fromUtf8("StackAll"))
        self.gridLayout_5.addWidget(self.StackAll, 6, 3, 1, 1)
        self.line_3 = QtGui.QFrame(self.BSP)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_5.addWidget(self.line_3, 7, 1, 1, 5)
        self.Stack = QtGui.QCheckBox(self.BSP)
        self.Stack.setObjectName(_fromUtf8("Stack"))
        self.gridLayout_5.addWidget(self.Stack, 6, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self.BSP)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_5.addWidget(self.line_5, 6, 4, 1, 1)
        self.ShowBoth = QtGui.QRadioButton(self.BSP)
        self.ShowBoth.setChecked(True)
        self.ShowBoth.setObjectName(_fromUtf8("ShowBoth"))
        self.gridLayout_5.addWidget(self.ShowBoth, 4, 1, 1, 1)
        self.ShowNormOnly = QtGui.QRadioButton(self.BSP)
        self.ShowNormOnly.setObjectName(_fromUtf8("ShowNormOnly"))
        self.gridLayout_5.addWidget(self.ShowNormOnly, 4, 3, 1, 1)
        self.ShowNonNorm = QtGui.QRadioButton(self.BSP)
        self.ShowNonNorm.setObjectName(_fromUtf8("ShowNonNorm"))
        self.gridLayout_5.addWidget(self.ShowNonNorm, 4, 5, 1, 1)
        self.DegreeBSP = QtGui.QSpinBox(self.BSP)
        self.DegreeBSP.setMinimum(1)
        self.DegreeBSP.setProperty("value", 4)
        self.DegreeBSP.setObjectName(_fromUtf8("DegreeBSP"))
        self.gridLayout_5.addWidget(self.DegreeBSP, 3, 3, 1, 3)
        self.BSPResetPlots = QtGui.QPushButton(self.BSP)
        self.BSPResetPlots.setObjectName(_fromUtf8("BSPResetPlots"))
        self.gridLayout_5.addWidget(self.BSPResetPlots, 8, 1, 1, 1)
        self.BSPPlot = QtGui.QPushButton(self.BSP)
        self.BSPPlot.setObjectName(_fromUtf8("BSPPlot"))
        self.gridLayout_5.addWidget(self.BSPPlot, 8, 3, 1, 3)
        self.Functions.addTab(self.BSP, _fromUtf8(""))
        self.Ccor = QtGui.QWidget()
        self.Ccor.setObjectName(_fromUtf8("Ccor"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Ccor)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.CCorTarget = QtGui.QLineEdit(self.Ccor)
        self.CCorTarget.setObjectName(_fromUtf8("CCorTarget"))
        self.gridLayout_7.addWidget(self.CCorTarget, 3, 0, 1, 6)
        self.ShiftLabel = QtGui.QLabel(self.Ccor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShiftLabel.sizePolicy().hasHeightForWidth())
        self.ShiftLabel.setSizePolicy(sizePolicy)
        self.ShiftLabel.setObjectName(_fromUtf8("ShiftLabel"))
        self.gridLayout_7.addWidget(self.ShiftLabel, 5, 0, 1, 1)
        self.CCorUseList = QtGui.QCheckBox(self.Ccor)
        self.CCorUseList.setObjectName(_fromUtf8("CCorUseList"))
        self.gridLayout_7.addWidget(self.CCorUseList, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.Ccor)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_7.addWidget(self.line_6, 4, 0, 1, 6)
        self.CorLabe = QtGui.QLabel(self.Ccor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CorLabe.sizePolicy().hasHeightForWidth())
        self.CorLabe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.CorLabe.setFont(font)
        self.CorLabe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.CorLabe.setAlignment(QtCore.Qt.AlignCenter)
        self.CorLabe.setObjectName(_fromUtf8("CorLabe"))
        self.gridLayout_7.addWidget(self.CorLabe, 0, 0, 1, 6)
        self.CCorList = QtGui.QLineEdit(self.Ccor)
        self.CCorList.setObjectName(_fromUtf8("CCorList"))
        self.gridLayout_7.addWidget(self.CCorList, 1, 5, 1, 1)
        self.CCorTemplate = QtGui.QLineEdit(self.Ccor)
        self.CCorTemplate.setObjectName(_fromUtf8("CCorTemplate"))
        self.gridLayout_7.addWidget(self.CCorTemplate, 2, 0, 1, 6)
        self.line_10 = QtGui.QFrame(self.Ccor)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_7.addWidget(self.line_10, 6, 4, 1, 1)
        self.line_9 = QtGui.QFrame(self.Ccor)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_7.addWidget(self.line_9, 6, 3, 1, 1)
        self.ShiftSize = QtGui.QSpinBox(self.Ccor)
        self.ShiftSize.setMinimum(50)
        self.ShiftSize.setMaximum(1000)
        self.ShiftSize.setSingleStep(2)
        self.ShiftSize.setProperty("value", 102)
        self.ShiftSize.setObjectName(_fromUtf8("ShiftSize"))
        self.gridLayout_7.addWidget(self.ShiftSize, 6, 0, 1, 1)
        self.ShowAll = QtGui.QCheckBox(self.Ccor)
        self.ShowAll.setObjectName(_fromUtf8("ShowAll"))
        self.gridLayout_7.addWidget(self.ShowAll, 10, 0, 1, 1)
        self.CCorRun = QtGui.QPushButton(self.Ccor)
        self.CCorRun.setObjectName(_fromUtf8("CCorRun"))
        self.gridLayout_7.addWidget(self.CCorRun, 10, 1, 1, 5)
        self.DegreeLabel = QtGui.QLabel(self.Ccor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DegreeLabel.sizePolicy().hasHeightForWidth())
        self.DegreeLabel.setSizePolicy(sizePolicy)
        self.DegreeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DegreeLabel.setObjectName(_fromUtf8("DegreeLabel"))
        self.gridLayout_7.addWidget(self.DegreeLabel, 5, 5, 1, 1)
        self.line_8 = QtGui.QFrame(self.Ccor)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_7.addWidget(self.line_8, 6, 2, 1, 1)
        self.CCorDegree = QtGui.QSpinBox(self.Ccor)
        self.CCorDegree.setMinimum(1)
        self.CCorDegree.setProperty("value", 4)
        self.CCorDegree.setObjectName(_fromUtf8("CCorDegree"))
        self.gridLayout_7.addWidget(self.CCorDegree, 6, 5, 1, 1)
        self.line_7 = QtGui.QFrame(self.Ccor)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_7.addWidget(self.line_7, 6, 1, 1, 1)
        self.line_11 = QtGui.QFrame(self.Ccor)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_7.addWidget(self.line_11, 7, 0, 1, 6)
        self.Functions.addTab(self.Ccor, _fromUtf8(""))
        self.GFit = QtGui.QWidget()
        self.GFit.setObjectName(_fromUtf8("GFit"))
        self.gridLayout_8 = QtGui.QGridLayout(self.GFit)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.UserLines = QtGui.QWidget(self.GFit)
        self.UserLines.setObjectName(_fromUtf8("UserLines"))
        self.gridLayout_11 = QtGui.QGridLayout(self.UserLines)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.UserLinesLabel = QtGui.QLabel(self.UserLines)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserLinesLabel.sizePolicy().hasHeightForWidth())
        self.UserLinesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.UserLinesLabel.setFont(font)
        self.UserLinesLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.UserLinesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UserLinesLabel.setObjectName(_fromUtf8("UserLinesLabel"))
        self.gridLayout_11.addWidget(self.UserLinesLabel, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.UserLines, 1, 1, 1, 1)
        self.SystemLines = QtGui.QWidget(self.GFit)
        self.SystemLines.setObjectName(_fromUtf8("SystemLines"))
        self.gridLayout_9 = QtGui.QGridLayout(self.SystemLines)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.HydrogenA = QtGui.QCheckBox(self.SystemLines)
        self.HydrogenA.setObjectName(_fromUtf8("HydrogenA"))
        self.gridLayout_9.addWidget(self.HydrogenA, 1, 0, 1, 1)
        self.AtmoOx = QtGui.QCheckBox(self.SystemLines)
        self.AtmoOx.setObjectName(_fromUtf8("AtmoOx"))
        self.gridLayout_9.addWidget(self.AtmoOx, 3, 0, 1, 1)
        self.He4685 = QtGui.QCheckBox(self.SystemLines)
        self.He4685.setObjectName(_fromUtf8("He4685"))
        self.gridLayout_9.addWidget(self.He4685, 5, 0, 1, 1)
        self.He5015 = QtGui.QCheckBox(self.SystemLines)
        self.He5015.setObjectName(_fromUtf8("He5015"))
        self.gridLayout_9.addWidget(self.He5015, 7, 0, 1, 1)
        self.HydrogenB = QtGui.QCheckBox(self.SystemLines)
        self.HydrogenB.setObjectName(_fromUtf8("HydrogenB"))
        self.gridLayout_9.addWidget(self.HydrogenB, 2, 0, 1, 1)
        self.He5875 = QtGui.QCheckBox(self.SystemLines)
        self.He5875.setObjectName(_fromUtf8("He5875"))
        self.gridLayout_9.addWidget(self.He5875, 4, 0, 1, 1)
        self.He4921 = QtGui.QCheckBox(self.SystemLines)
        self.He4921.setObjectName(_fromUtf8("He4921"))
        self.gridLayout_9.addWidget(self.He4921, 6, 0, 1, 1)
        self.SystemLinesLabel = QtGui.QLabel(self.SystemLines)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SystemLinesLabel.sizePolicy().hasHeightForWidth())
        self.SystemLinesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.SystemLinesLabel.setFont(font)
        self.SystemLinesLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SystemLinesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SystemLinesLabel.setObjectName(_fromUtf8("SystemLinesLabel"))
        self.gridLayout_9.addWidget(self.SystemLinesLabel, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.SystemLines, 1, 0, 1, 1)
        self.GfitLabel = QtGui.QLabel(self.GFit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GfitLabel.sizePolicy().hasHeightForWidth())
        self.GfitLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.GfitLabel.setFont(font)
        self.GfitLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.GfitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GfitLabel.setObjectName(_fromUtf8("GfitLabel"))
        self.gridLayout_8.addWidget(self.GfitLabel, 0, 0, 1, 2)
        self.GFitPlotButtons = QtGui.QWidget(self.GFit)
        self.GFitPlotButtons.setObjectName(_fromUtf8("GFitPlotButtons"))
        self.gridLayout_12 = QtGui.QGridLayout(self.GFitPlotButtons)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.GFitRun = QtGui.QPushButton(self.GFitPlotButtons)
        self.GFitRun.setObjectName(_fromUtf8("GFitRun"))
        self.gridLayout_12.addWidget(self.GFitRun, 0, 0, 1, 1)
        self.GFitRun.raise_()
        self.gridLayout_8.addWidget(self.GFitPlotButtons, 2, 1, 1, 1)
        self.LineAdditions = QtGui.QWidget(self.GFit)
        self.LineAdditions.setObjectName(_fromUtf8("LineAdditions"))
        self.gridLayout_10 = QtGui.QGridLayout(self.LineAdditions)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.AddLine = QtGui.QPushButton(self.LineAdditions)
        self.AddLine.setObjectName(_fromUtf8("AddLine"))
        self.gridLayout_10.addWidget(self.AddLine, 4, 0, 1, 2)
        self.LineLocation = QtGui.QLineEdit(self.LineAdditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineLocation.sizePolicy().hasHeightForWidth())
        self.LineLocation.setSizePolicy(sizePolicy)
        self.LineLocation.setObjectName(_fromUtf8("LineLocation"))
        self.gridLayout_10.addWidget(self.LineLocation, 3, 0, 1, 1)
        self.LineAdditionsLabel = QtGui.QLabel(self.LineAdditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineAdditionsLabel.sizePolicy().hasHeightForWidth())
        self.LineAdditionsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.LineAdditionsLabel.setFont(font)
        self.LineAdditionsLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LineAdditionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LineAdditionsLabel.setObjectName(_fromUtf8("LineAdditionsLabel"))
        self.gridLayout_10.addWidget(self.LineAdditionsLabel, 0, 0, 1, 2)
        self.LineName = QtGui.QLineEdit(self.LineAdditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineName.sizePolicy().hasHeightForWidth())
        self.LineName.setSizePolicy(sizePolicy)
        self.LineName.setObjectName(_fromUtf8("LineName"))
        self.gridLayout_10.addWidget(self.LineName, 1, 0, 1, 2)
        self.LineWindow = QtGui.QDoubleSpinBox(self.LineAdditions)
        self.LineWindow.setMinimum(0.05)
        self.LineWindow.setSingleStep(0.01)
        self.LineWindow.setProperty("value", 0.1)
        self.LineWindow.setObjectName(_fromUtf8("LineWindow"))
        self.gridLayout_10.addWidget(self.LineWindow, 3, 1, 1, 1)
        self.LineWindowize = QtGui.QLabel(self.LineAdditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineWindowize.sizePolicy().hasHeightForWidth())
        self.LineWindowize.setSizePolicy(sizePolicy)
        self.LineWindowize.setObjectName(_fromUtf8("LineWindowize"))
        self.gridLayout_10.addWidget(self.LineWindowize, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.LineAdditions, 2, 0, 1, 1)
        self.Functions.addTab(self.GFit, _fromUtf8(""))
        self.OrbitalFit = QtGui.QWidget()
        self.OrbitalFit.setObjectName(_fromUtf8("OrbitalFit"))
        self.gridLayout_13 = QtGui.QGridLayout(self.OrbitalFit)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.EccentricityValue = QtGui.QDoubleSpinBox(self.OrbitalFit)
        self.EccentricityValue.setMaximum(0.0)
        self.EccentricityValue.setSingleStep(0.0)
        self.EccentricityValue.setObjectName(_fromUtf8("EccentricityValue"))
        self.gridLayout_13.addWidget(self.EccentricityValue, 1, 2, 1, 1)
        self.OrbFitRun = QtGui.QPushButton(self.OrbitalFit)
        self.OrbFitRun.setObjectName(_fromUtf8("OrbFitRun"))
        self.gridLayout_13.addWidget(self.OrbFitRun, 8, 0, 1, 4)
        self.lineEdit_8 = QtGui.QLineEdit(self.OrbitalFit)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_13.addWidget(self.lineEdit_8, 3, 0, 1, 3)
        self.SinTrend = QtGui.QRadioButton(self.OrbitalFit)
        self.SinTrend.setObjectName(_fromUtf8("SinTrend"))
        self.gridLayout_13.addWidget(self.SinTrend, 6, 1, 1, 1)
        self.OrbClearAll = QtGui.QPushButton(self.OrbitalFit)
        self.OrbClearAll.setObjectName(_fromUtf8("OrbClearAll"))
        self.gridLayout_13.addWidget(self.OrbClearAll, 7, 2, 1, 2)
        self.FreeEccentricity = QtGui.QCheckBox(self.OrbitalFit)
        self.FreeEccentricity.setCheckable(False)
        self.FreeEccentricity.setObjectName(_fromUtf8("FreeEccentricity"))
        self.gridLayout_13.addWidget(self.FreeEccentricity, 1, 3, 1, 1)
        self.Lineartrend = QtGui.QRadioButton(self.OrbitalFit)
        self.Lineartrend.setObjectName(_fromUtf8("Lineartrend"))
        self.gridLayout_13.addWidget(self.Lineartrend, 6, 0, 1, 1)
        self.PhaseFoldyn = QtGui.QCheckBox(self.OrbitalFit)
        self.PhaseFoldyn.setObjectName(_fromUtf8("PhaseFoldyn"))
        self.gridLayout_13.addWidget(self.PhaseFoldyn, 6, 2, 1, 1)
        self.OrbClearTrends = QtGui.QPushButton(self.OrbitalFit)
        self.OrbClearTrends.setObjectName(_fromUtf8("OrbClearTrends"))
        self.gridLayout_13.addWidget(self.OrbClearTrends, 7, 0, 1, 2)
        self.OrbBrowse = QtGui.QToolButton(self.OrbitalFit)
        self.OrbBrowse.setObjectName(_fromUtf8("OrbBrowse"))
        self.gridLayout_13.addWidget(self.OrbBrowse, 4, 3, 1, 1)
        self.FreePeriod = QtGui.QCheckBox(self.OrbitalFit)
        self.FreePeriod.setCheckable(False)
        self.FreePeriod.setChecked(False)
        self.FreePeriod.setObjectName(_fromUtf8("FreePeriod"))
        self.gridLayout_13.addWidget(self.FreePeriod, 3, 3, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.OrbitalFit)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_13.addWidget(self.lineEdit_9, 4, 0, 1, 3)
        self.EccentricityLabel = QtGui.QLabel(self.OrbitalFit)
        self.EccentricityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EccentricityLabel.setObjectName(_fromUtf8("EccentricityLabel"))
        self.gridLayout_13.addWidget(self.EccentricityLabel, 1, 1, 1, 1)
        self.orbitalFitLabel = QtGui.QLabel(self.OrbitalFit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orbitalFitLabel.sizePolicy().hasHeightForWidth())
        self.orbitalFitLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.orbitalFitLabel.setFont(font)
        self.orbitalFitLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.orbitalFitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.orbitalFitLabel.setObjectName(_fromUtf8("orbitalFitLabel"))
        self.gridLayout_13.addWidget(self.orbitalFitLabel, 0, 0, 1, 4)
        self.Functions.addTab(self.OrbitalFit, _fromUtf8(""))
        self.Settings = QtGui.QWidget()
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.gridLayout_14 = QtGui.QGridLayout(self.Settings)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.SAULinfo = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAULinfo.sizePolicy().hasHeightForWidth())
        self.SAULinfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monaco"))
        font.setPointSize(15)
        self.SAULinfo.setFont(font)
        self.SAULinfo.setFrameShape(QtGui.QFrame.NoFrame)
        self.SAULinfo.setFrameShadow(QtGui.QFrame.Plain)
        self.SAULinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.SAULinfo.setObjectName(_fromUtf8("SAULinfo"))
        self.gridLayout_14.addWidget(self.SAULinfo, 1, 0, 1, 1)
        self.SettingsLabel = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsLabel.sizePolicy().hasHeightForWidth())
        self.SettingsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(20)
        self.SettingsLabel.setFont(font)
        self.SettingsLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SettingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SettingsLabel.setObjectName(_fromUtf8("SettingsLabel"))
        self.gridLayout_14.addWidget(self.SettingsLabel, 0, 0, 1, 1)
        self.SettingsBox = QtGui.QWidget(self.Settings)
        self.SettingsBox.setObjectName(_fromUtf8("SettingsBox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.SettingsBox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.PLACEHOLDER = QtGui.QLabel(self.SettingsBox)
        self.PLACEHOLDER.setObjectName(_fromUtf8("PLACEHOLDER"))
        self.gridLayout_15.addWidget(self.PLACEHOLDER, 0, 2, 1, 1)
        self.Secret = QtGui.QPushButton(self.SettingsBox)
        self.Secret.setObjectName(_fromUtf8("Secret"))
        self.gridLayout_15.addWidget(self.Secret, 1, 2, 1, 1)
        self.gridLayout_14.addWidget(self.SettingsBox, 2, 0, 1, 1)
        self.Functions.addTab(self.Settings, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.Functions, 0, 2, 1, 1)
        self.Terminal.raise_()
        self.Terminal.raise_()
        self.Functions.raise_()
        self.gridLayout.addWidget(self.AdvancedFunctions, 0, 1, 2, 1)
        self.PlotArea = QtGui.QWidget(self.Main)
        self.PlotArea.setObjectName(_fromUtf8("PlotArea"))
        self.gridLayout_19 = QtGui.QGridLayout(self.PlotArea)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.PlotOne = QtGui.QWidget(self.PlotArea)
        self.PlotOne.setObjectName(_fromUtf8("PlotOne"))
        self.gridLayout_19.addWidget(self.PlotOne, 1, 0, 1, 1)
        self.PlotTwo = QtGui.QWidget(self.PlotArea)
        self.PlotTwo.setObjectName(_fromUtf8("PlotTwo"))
        self.gridLayout_19.addWidget(self.PlotTwo, 2, 0, 1, 1)
        self.PlotTwo.raise_()
        self.PlotOne.raise_()
        self.PlotTwo.raise_()
        self.gridLayout.addWidget(self.PlotArea, 0, 2, 3, 2)
        SAUL.setCentralWidget(self.Main)
        self.menubar = QtGui.QMenuBar(SAUL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1674, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOpen_file = QtGui.QMenu(self.menuFile)
        self.menuOpen_file.setObjectName(_fromUtf8("menuOpen_file"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSAUL = QtGui.QMenu(self.menubar)
        self.menuSAUL.setObjectName(_fromUtf8("menuSAUL"))
        self.menuSource_Code = QtGui.QMenu(self.menuSAUL)
        self.menuSource_Code.setObjectName(_fromUtf8("menuSource_Code"))
        self.menuIndividual_File = QtGui.QMenu(self.menuSource_Code)
        self.menuIndividual_File.setObjectName(_fromUtf8("menuIndividual_File"))
        self.menuGuiFiles = QtGui.QMenu(self.menuIndividual_File)
        self.menuGuiFiles.setObjectName(_fromUtf8("menuGuiFiles"))
        SAUL.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SAUL)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SAUL.setStatusBar(self.statusbar)
        self.actionSave_Plots = QtGui.QAction(SAUL)
        self.actionSave_Plots.setObjectName(_fromUtf8("actionSave_Plots"))
        self.actionSave_ASCII_Fit = QtGui.QAction(SAUL)
        self.actionSave_ASCII_Fit.setObjectName(_fromUtf8("actionSave_ASCII_Fit"))
        self.actionReload = QtGui.QAction(SAUL)
        self.actionReload.setObjectName(_fromUtf8("actionReload"))
        self.actionQuit_a = QtGui.QAction(SAUL)
        self.actionQuit_a.setObjectName(_fromUtf8("actionQuit_a"))
        self.actionSave_Plots_2 = QtGui.QAction(SAUL)
        self.actionSave_Plots_2.setObjectName(_fromUtf8("actionSave_Plots_2"))
        self.actionOpen_RV_file = QtGui.QAction(SAUL)
        self.actionOpen_RV_file.setObjectName(_fromUtf8("actionOpen_RV_file"))
        self.actionOpen_Fits_File = QtGui.QAction(SAUL)
        self.actionOpen_Fits_File.setObjectName(_fromUtf8("actionOpen_Fits_File"))
        self.actionOpen_ASCII_file = QtGui.QAction(SAUL)
        self.actionOpen_ASCII_file.setObjectName(_fromUtf8("actionOpen_ASCII_file"))
        self.actionCopy = QtGui.QAction(SAUL)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(SAUL)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(SAUL)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionFull_Screen = QtGui.QAction(SAUL)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.actionHide = QtGui.QAction(SAUL)
        self.actionHide.setObjectName(_fromUtf8("actionHide"))
        self.actionReset_Windows = QtGui.QAction(SAUL)
        self.actionReset_Windows.setObjectName(_fromUtf8("actionReset_Windows"))
        self.actionREADME = QtGui.QAction(SAUL)
        self.actionREADME.setObjectName(_fromUtf8("actionREADME"))
        self.actionInfo = QtGui.QAction(SAUL)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionCommand_List = QtGui.QAction(SAUL)
        self.actionCommand_List.setObjectName(_fromUtf8("actionCommand_List"))
        self.actionAll = QtGui.QAction(SAUL)
        self.actionAll.setObjectName(_fromUtf8("actionAll"))
        self.actionBPlot_py = QtGui.QAction(SAUL)
        self.actionBPlot_py.setObjectName(_fromUtf8("actionBPlot_py"))
        self.actionGuiFunction_py = QtGui.QAction(SAUL)
        self.actionGuiFunction_py.setObjectName(_fromUtf8("actionGuiFunction_py"))
        self.actionGeneral_py = QtGui.QAction(SAUL)
        self.actionGeneral_py.setObjectName(_fromUtf8("actionGeneral_py"))
        self.actionConsollControl_py = QtGui.QAction(SAUL)
        self.actionConsollControl_py.setObjectName(_fromUtf8("actionConsollControl_py"))
        self.actionAstrolib_py = QtGui.QAction(SAUL)
        self.actionAstrolib_py.setObjectName(_fromUtf8("actionAstrolib_py"))
        self.actionMainWindow_py = QtGui.QAction(SAUL)
        self.actionMainWindow_py.setObjectName(_fromUtf8("actionMainWindow_py"))
        self.actionCorrelation2_py = QtGui.QAction(SAUL)
        self.actionCorrelation2_py.setObjectName(_fromUtf8("actionCorrelation2_py"))
        self.actionYnadcanve_py = QtGui.QAction(SAUL)
        self.actionYnadcanve_py.setObjectName(_fromUtf8("actionYnadcanve_py"))
        self.actionJumptoorder_py = QtGui.QAction(SAUL)
        self.actionJumptoorder_py.setObjectName(_fromUtf8("actionJumptoorder_py"))
        self.actionGaussian_py = QtGui.QAction(SAUL)
        self.actionGaussian_py.setObjectName(_fromUtf8("actionGaussian_py"))
        self.actionMultiPlotViewr_py = QtGui.QAction(SAUL)
        self.actionMultiPlotViewr_py.setObjectName(_fromUtf8("actionMultiPlotViewr_py"))
        self.actionTerminal_Breakaway = QtGui.QAction(SAUL)
        self.actionTerminal_Breakaway.setObjectName(_fromUtf8("actionTerminal_Breakaway"))
        self.actionUse_Matplotlib_standard = QtGui.QAction(SAUL)
        self.actionUse_Matplotlib_standard.setCheckable(True)
        self.actionUse_Matplotlib_standard.setObjectName(_fromUtf8("actionUse_Matplotlib_standard"))
        self.actionOpen_Cross_Correlation_BreakAway_settings = QtGui.QAction(SAUL)
        self.actionOpen_Cross_Correlation_BreakAway_settings.setObjectName(_fromUtf8("actionOpen_Cross_Correlation_BreakAway_settings"))
        self.menuOpen_file.addAction(self.actionOpen_RV_file)
        self.menuOpen_file.addAction(self.actionOpen_Fits_File)
        self.menuOpen_file.addAction(self.actionOpen_ASCII_file)
        self.menuFile.addAction(self.actionSave_Plots_2)
        self.menuFile.addAction(self.actionSave_ASCII_Fit)
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addAction(self.menuOpen_file.menuAction())
        self.menuFile.addAction(self.actionSave_Plots)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuWindow.addAction(self.actionFull_Screen)
        self.menuWindow.addAction(self.actionHide)
        self.menuWindow.addAction(self.actionReset_Windows)
        self.menuHelp.addAction(self.actionREADME)
        self.menuHelp.addAction(self.actionInfo)
        self.menuHelp.addAction(self.actionCommand_List)
        self.menuGuiFiles.addAction(self.actionMainWindow_py)
        self.menuGuiFiles.addAction(self.actionCorrelation2_py)
        self.menuGuiFiles.addAction(self.actionYnadcanve_py)
        self.menuGuiFiles.addAction(self.actionJumptoorder_py)
        self.menuGuiFiles.addAction(self.actionGaussian_py)
        self.menuGuiFiles.addAction(self.actionMultiPlotViewr_py)
        self.menuIndividual_File.addAction(self.actionBPlot_py)
        self.menuIndividual_File.addAction(self.actionGuiFunction_py)
        self.menuIndividual_File.addAction(self.actionGeneral_py)
        self.menuIndividual_File.addAction(self.actionConsollControl_py)
        self.menuIndividual_File.addAction(self.actionAstrolib_py)
        self.menuIndividual_File.addAction(self.menuGuiFiles.menuAction())
        self.menuSource_Code.addAction(self.actionAll)
        self.menuSource_Code.addAction(self.menuIndividual_File.menuAction())
        self.menuSAUL.addAction(self.menuSource_Code.menuAction())
        self.menuSAUL.addAction(self.actionTerminal_Breakaway)
        self.menuSAUL.addAction(self.actionUse_Matplotlib_standard)
        self.menuSAUL.addAction(self.actionOpen_Cross_Correlation_BreakAway_settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSAUL.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SAUL)
        self.Functions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SAUL)

    def retranslateUi(self, SAUL):
        SAUL.setWindowTitle(_translate("SAUL", "SAUL", None))
        SAUL.setToolTip(_translate("SAUL", "Spectral Analysis UtiLity (SAUL)", None))
        self.Command.setPlaceholderText(_translate("SAUL", ">", None))
        self.TerminalLabel.setText(_translate("SAUL", "Terminal", None))
        self.PlotControllabel.setText(_translate("SAUL", "Plot Controls", None))
        self.PlotTwoShowingLabel.setText(_translate("SAUL", "Plot Two Showing:", None))
        self.SavePlotTwo.setText(_translate("SAUL", "Save Plot Two", None))
        self.SavePlotOne.setText(_translate("SAUL", "Save Plot One", None))
        self.WhatIsOnPlotOne.setText(_translate("SAUL", "N/A", None))
        self.JumpToOrder.setText(_translate("SAUL", "Jump to order", None))
        self.WhatIsOnePlotTwo.setText(_translate("SAUL", "N/A", None))
        self.OrderAdvance.setText(_translate("SAUL", "Order Advance (d)", None))
        self.PlotOneShowingLabel.setText(_translate("SAUL", "Plot one Showing:", None))
        self.OrderRetreate.setText(_translate("SAUL", "Order Retreate (a)", None))
        self.ToggleSpectra.setText(_translate("SAUL", "Toggle Spectra on (c)", None))
        self.ReastFit.setText(_translate("SAUL", "Reset Fit (o)", None))
        self.RemoveSpectra.setText(_translate("SAUL", "Remove Spectra (q)", None))
        self.AddSpectra.setText(_translate("SAUL", " Add Spectra (e)", None))
        self.ClearPlots.setText(_translate("SAUL", "Clear Plots", None))
        self.ChangeDirectory.setText(_translate("SAUL", "Change Directory", None))
        self.GeneratePathFile.setText(_translate("SAUL", "Generate Path Files", None))
        self.Quit.setText(_translate("SAUL", "Quit", None))
        self.Reload.setText(_translate("SAUL", "Reload", None))
        self.GF.setText(_translate("SAUL", "General Control", None))
        self.DataPathsLabel.setText(_translate("SAUL", "Data Paths:", None))
        self.Normalizeyn.setText(_translate("SAUL", "Normalize Spectra", None))
        self.BSPPath.setToolTip(_translate("SAUL", "Path to fits file, or a path to a path file, if you want to overllay exposures enter a path to a path file", None))
        self.BSPPath.setPlaceholderText(_translate("SAUL", "Path to fits file, or path to \'Path file\'", None))
        self.NumToStack.setToolTip(_translate("SAUL", "Initial number of exposure to overlay", None))
        self.BSPLabel.setText(_translate("SAUL", "Basic Spectreal Plotter", None))
        self.StackAll.setToolTip(_translate("SAUL", "Overlay all exposures inintally", None))
        self.StackAll.setText(_translate("SAUL", "All", None))
        self.Stack.setToolTip(_translate("SAUL", "Overlay exposures with a y offset to see compare them quickly", None))
        self.Stack.setText(_translate("SAUL", "Overlay exposure", None))
        self.ShowBoth.setToolTip(_translate("SAUL", "Display both the Nomarlized spectra as well as the non normalized specra", None))
        self.ShowBoth.setText(_translate("SAUL", "Both Plots", None))
        self.ShowNormOnly.setToolTip(_translate("SAUL", "Only display the normalized spectra", None))
        self.ShowNormOnly.setText(_translate("SAUL", "Only Notmalized", None))
        self.ShowNonNorm.setToolTip(_translate("SAUL", "Only display the non normalized spectra", None))
        self.ShowNonNorm.setText(_translate("SAUL", "Only NonNormalze", None))
        self.DegreeBSP.setToolTip(_translate("SAUL", "Degree to normalize function to", None))
        self.BSPResetPlots.setToolTip(_translate("SAUL", "Reset the plot window", None))
        self.BSPResetPlots.setText(_translate("SAUL", "Reset Plots", None))
        self.BSPPlot.setToolTip(_translate("SAUL", "Run Plot in plot window", None))
        self.BSPPlot.setText(_translate("SAUL", "Run Plot", None))
        self.Functions.setTabText(self.Functions.indexOf(self.BSP), _translate("SAUL", "Spectum Plot", None))
        self.CCorTarget.setPlaceholderText(_translate("SAUL", "Enter Target Path", None))
        self.ShiftLabel.setText(_translate("SAUL", "Shift Size", None))
        self.CCorUseList.setText(_translate("SAUL", "Use List", None))
        self.CorLabe.setText(_translate("SAUL", "Cross Correlation", None))
        self.CCorList.setPlaceholderText(_translate("SAUL", "Enter Path to Path File", None))
        self.CCorTemplate.setPlaceholderText(_translate("SAUL", "Enter Template Path", None))
        self.ShowAll.setText(_translate("SAUL", "All Orders", None))
        self.CCorRun.setText(_translate("SAUL", "Run Correlation", None))
        self.DegreeLabel.setText(_translate("SAUL", "Normilization Degree", None))
        self.Functions.setTabText(self.Functions.indexOf(self.Ccor), _translate("SAUL", "C-Cor", None))
        self.UserLinesLabel.setText(_translate("SAUL", "User Lines", None))
        self.HydrogenA.setText(_translate("SAUL", "Hydrogen Alpha", None))
        self.AtmoOx.setText(_translate("SAUL", "Atmospheric Oxygen", None))
        self.He4685.setText(_translate("SAUL", "He 4685.92", None))
        self.He5015.setText(_translate("SAUL", "He 5015.68", None))
        self.HydrogenB.setText(_translate("SAUL", "Hydrogen Beta", None))
        self.He5875.setText(_translate("SAUL", "He 5875.62", None))
        self.He4921.setText(_translate("SAUL", "He 4921.93", None))
        self.SystemLinesLabel.setText(_translate("SAUL", "System Lines", None))
        self.GfitLabel.setText(_translate("SAUL", "Gaussian Fitting", None))
        self.GFitRun.setText(_translate("SAUL", "Fit and Plot", None))
        self.AddLine.setText(_translate("SAUL", "Add Line", None))
        self.LineLocation.setToolTip(_translate("SAUL", "Actual Location of line on non shifted spectrum (Angstroms)", None))
        self.LineLocation.setPlaceholderText(_translate("SAUL", "Line Location", None))
        self.LineAdditionsLabel.setText(_translate("SAUL", "Line Additions", None))
        self.LineName.setToolTip(_translate("SAUL", "Name of line that user will see", None))
        self.LineName.setPlaceholderText(_translate("SAUL", "Line Label", None))
        self.LineWindow.setToolTip(_translate("SAUL", "Size Arond line (Angstroms)", None))
        self.LineWindowize.setText(_translate("SAUL", "Win Size", None))
        self.Functions.setTabText(self.Functions.indexOf(self.GFit), _translate("SAUL", "G-Fit", None))
        self.EccentricityValue.setToolTip(_translate("SAUL", "Eccentricity", None))
        self.OrbFitRun.setText(_translate("SAUL", "Run Orbital fit", None))
        self.lineEdit_8.setToolTip(_translate("SAUL", "Period in days", None))
        self.lineEdit_8.setPlaceholderText(_translate("SAUL", "Period (days)", None))
        self.SinTrend.setText(_translate("SAUL", "Sin Trend", None))
        self.OrbClearAll.setText(_translate("SAUL", "Clear All Parameters", None))
        self.FreeEccentricity.setToolTip(_translate("SAUL", "Make the Eccentricity a Free parameter", None))
        self.FreeEccentricity.setText(_translate("SAUL", "Free", None))
        self.Lineartrend.setText(_translate("SAUL", "Linear Trend", None))
        self.PhaseFoldyn.setText(_translate("SAUL", "Phase Fold", None))
        self.OrbClearTrends.setText(_translate("SAUL", "Clear All Trends", None))
        self.OrbBrowse.setToolTip(_translate("SAUL", "Browse computer for RV files", None))
        self.OrbBrowse.setText(_translate("SAUL", "...", None))
        self.FreePeriod.setToolTip(_translate("SAUL", "Make the period a free parameter", None))
        self.FreePeriod.setText(_translate("SAUL", "Free", None))
        self.lineEdit_9.setToolTip(_translate("SAUL", "Path to RV file", None))
        self.lineEdit_9.setPlaceholderText(_translate("SAUL", "RV file Path", None))
        self.EccentricityLabel.setText(_translate("SAUL", "Eccentricity:", None))
        self.orbitalFitLabel.setText(_translate("SAUL", "Orbital Fitter", None))
        self.Functions.setTabText(self.Functions.indexOf(self.OrbitalFit), _translate("SAUL", "Orb-Fit", None))
        self.SAULinfo.setText(_translate("SAUL", "SAUL Alpha 0.8 \n"
"Devloped at High Point Univerisy by \n"
"Thomas Boudreaux and Padraig Clancy", None))
        self.SettingsLabel.setText(_translate("SAUL", "Settings", None))
        self.PLACEHOLDER.setText(_translate("SAUL", "Future home of settings", None))
        self.Secret.setText(_translate("SAUL", "Answer", None))
        self.Functions.setTabText(self.Functions.indexOf(self.Settings), _translate("SAUL", "Settings", None))
        self.menuFile.setTitle(_translate("SAUL", "File", None))
        self.menuOpen_file.setTitle(_translate("SAUL", "open file", None))
        self.menuEdit.setTitle(_translate("SAUL", "Edit", None))
        self.menuWindow.setTitle(_translate("SAUL", "Window", None))
        self.menuHelp.setTitle(_translate("SAUL", "Help", None))
        self.menuSAUL.setTitle(_translate("SAUL", "SAUL", None))
        self.menuSource_Code.setTitle(_translate("SAUL", "Source Code", None))
        self.menuIndividual_File.setTitle(_translate("SAUL", "Individual File", None))
        self.menuGuiFiles.setTitle(_translate("SAUL", "GuiFiles", None))
        self.actionSave_Plots.setText(_translate("SAUL", "quit (command-q)", None))
        self.actionSave_ASCII_Fit.setText(_translate("SAUL", "Save ASCII Fit", None))
        self.actionReload.setText(_translate("SAUL", "reload (command-r)", None))
        self.actionQuit_a.setText(_translate("SAUL", "quit (a)", None))
        self.actionSave_Plots_2.setText(_translate("SAUL", "Save Plots", None))
        self.actionOpen_RV_file.setText(_translate("SAUL", "Open RV file", None))
        self.actionOpen_Fits_File.setText(_translate("SAUL", "Open Fits File", None))
        self.actionOpen_ASCII_file.setText(_translate("SAUL", "Open ASCII file", None))
        self.actionCopy.setText(_translate("SAUL", "Copy", None))
        self.actionPaste.setText(_translate("SAUL", "Paste", None))
        self.actionCut.setText(_translate("SAUL", "Cut", None))
        self.actionFull_Screen.setText(_translate("SAUL", "Full Screen", None))
        self.actionHide.setText(_translate("SAUL", "Hide", None))
        self.actionReset_Windows.setText(_translate("SAUL", "Reset Windows", None))
        self.actionREADME.setText(_translate("SAUL", "README", None))
        self.actionInfo.setText(_translate("SAUL", "info", None))
        self.actionCommand_List.setText(_translate("SAUL", "Command List", None))
        self.actionAll.setText(_translate("SAUL", "All", None))
        self.actionBPlot_py.setText(_translate("SAUL", "BPlot.py", None))
        self.actionGuiFunction_py.setText(_translate("SAUL", "GuiFunction.py", None))
        self.actionGeneral_py.setText(_translate("SAUL", "General.py", None))
        self.actionConsollControl_py.setText(_translate("SAUL", "ConsollControl.py", None))
        self.actionAstrolib_py.setText(_translate("SAUL", "Astrolib.py", None))
        self.actionMainWindow_py.setText(_translate("SAUL", "MainWindow.py", None))
        self.actionCorrelation2_py.setText(_translate("SAUL", "Correlation2.py", None))
        self.actionYnadcanve_py.setText(_translate("SAUL", "ynadcanve.py", None))
        self.actionJumptoorder_py.setText(_translate("SAUL", "jumptoorder.py", None))
        self.actionGaussian_py.setText(_translate("SAUL", "Gaussian.py", None))
        self.actionMultiPlotViewr_py.setText(_translate("SAUL", "MultiPlotViewr.py", None))
        self.actionTerminal_Breakaway.setText(_translate("SAUL", "Terminal Breakaway", None))
        self.actionUse_Matplotlib_standard.setText(_translate("SAUL", "Use Matplotlib standard", None))
        self.actionOpen_Cross_Correlation_BreakAway_settings.setText(_translate("SAUL", "Open Cross Correlation BreakAway settings", None))

