# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Header(object):
    def setupUi(self, Header):
        Header.setObjectName(_fromUtf8("Header"))
        Header.resize(635, 774)
        self.gridLayout = QtGui.QGridLayout(Header)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.singleFileInput = QtGui.QLineEdit(Header)
        self.singleFileInput.setObjectName(_fromUtf8("singleFileInput"))
        self.gridLayout.addWidget(self.singleFileInput, 4, 0, 1, 8)
        self.PathFileProgress = QtGui.QProgressBar(Header)
        self.PathFileProgress.setProperty("value", 0)
        self.PathFileProgress.setObjectName(_fromUtf8("PathFileProgress"))
        self.gridLayout.addWidget(self.PathFileProgress, 10, 0, 1, 3)
        self.amplitude = QtGui.QSpinBox(Header)
        self.amplitude.setObjectName(_fromUtf8("amplitude"))
        self.gridLayout.addWidget(self.amplitude, 12, 4, 1, 1)
        self.label = QtGui.QLabel(Header)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 12, 0, 1, 2)
        self.label_2 = QtGui.QLabel(Header)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 10, 4, 1, 1)
        self.UserFunction2 = QtGui.QPushButton(Header)
        self.UserFunction2.setObjectName(_fromUtf8("UserFunction2"))
        self.gridLayout.addWidget(self.UserFunction2, 10, 10, 1, 1)
        self.UseFunction1 = QtGui.QPushButton(Header)
        self.UseFunction1.setObjectName(_fromUtf8("UseFunction1"))
        self.gridLayout.addWidget(self.UseFunction1, 10, 9, 1, 1)
        self.label_6 = QtGui.QLabel(Header)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 9, 9, 1, 2)
        self.label_3 = QtGui.QLabel(Header)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 24, 5, 1, 2)
        self.pathListInput = QtGui.QLineEdit(Header)
        self.pathListInput.setObjectName(_fromUtf8("pathListInput"))
        self.gridLayout.addWidget(self.pathListInput, 2, 0, 1, 8)
        self.allStack = QtGui.QCheckBox(Header)
        self.allStack.setObjectName(_fromUtf8("allStack"))
        self.gridLayout.addWidget(self.allStack, 2, 10, 1, 1)
        self.line_5 = QtGui.QFrame(Header)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 9, 8, 4, 1)
        self.userFuntion4 = QtGui.QPushButton(Header)
        self.userFuntion4.setObjectName(_fromUtf8("userFuntion4"))
        self.gridLayout.addWidget(self.userFuntion4, 12, 10, 1, 1)
        self.UserFuntion3 = QtGui.QPushButton(Header)
        self.UserFuntion3.setObjectName(_fromUtf8("UserFuntion3"))
        self.gridLayout.addWidget(self.UserFuntion3, 12, 9, 1, 1)
        self.info = QtGui.QPushButton(Header)
        self.info.setObjectName(_fromUtf8("info"))
        self.gridLayout.addWidget(self.info, 17, 10, 1, 1)
        self.numStack = QtGui.QSpinBox(Header)
        self.numStack.setMinimum(1)
        self.numStack.setObjectName(_fromUtf8("numStack"))
        self.gridLayout.addWidget(self.numStack, 2, 9, 1, 1)
        self.listWidget = QtGui.QListWidget(Header)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout.addWidget(self.listWidget, 16, 0, 5, 10)
        self.line_4 = QtGui.QFrame(Header)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 15, 8, 1, 1)
        self.quitBut = QtGui.QPushButton(Header)
        self.quitBut.setObjectName(_fromUtf8("quitBut"))
        self.gridLayout.addWidget(self.quitBut, 20, 10, 1, 1)
        self.Reset = QtGui.QPushButton(Header)
        self.Reset.setObjectName(_fromUtf8("Reset"))
        self.gridLayout.addWidget(self.Reset, 16, 10, 1, 1)
        self.generatePathFiles = QtGui.QPushButton(Header)
        self.generatePathFiles.setObjectName(_fromUtf8("generatePathFiles"))
        self.gridLayout.addWidget(self.generatePathFiles, 9, 0, 1, 3)
        self.FunctionFit = QtGui.QCheckBox(Header)
        self.FunctionFit.setObjectName(_fromUtf8("FunctionFit"))
        self.gridLayout.addWidget(self.FunctionFit, 9, 4, 1, 2)
        self.line_3 = QtGui.QFrame(Header)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 9, 3, 4, 1)
        self.StackNumberLabel = QtGui.QLabel(Header)
        self.StackNumberLabel.setObjectName(_fromUtf8("StackNumberLabel"))
        self.gridLayout.addWidget(self.StackNumberLabel, 1, 9, 1, 2)
        self.label_4 = QtGui.QLabel(Header)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 9, 1, 2)
        self.singleFileLabel = QtGui.QLabel(Header)
        self.singleFileLabel.setObjectName(_fromUtf8("singleFileLabel"))
        self.gridLayout.addWidget(self.singleFileLabel, 3, 0, 1, 1)
        self.function4 = QtGui.QPushButton(Header)
        self.function4.setObjectName(_fromUtf8("function4"))
        self.gridLayout.addWidget(self.function4, 12, 5, 1, 1)
        self.function1 = QtGui.QPushButton(Header)
        self.function1.setObjectName(_fromUtf8("function1"))
        self.gridLayout.addWidget(self.function1, 10, 5, 1, 1)
        self.startOrd = QtGui.QSpinBox(Header)
        self.startOrd.setMinimum(1)
        self.startOrd.setMaximum(62)
        self.startOrd.setObjectName(_fromUtf8("startOrd"))
        self.gridLayout.addWidget(self.startOrd, 4, 9, 1, 1)
        self.plotBut = QtGui.QPushButton(Header)
        self.plotBut.setObjectName(_fromUtf8("plotBut"))
        self.gridLayout.addWidget(self.plotBut, 19, 10, 1, 1)
        self.consol = QtGui.QTextBrowser(Header)
        self.consol.setObjectName(_fromUtf8("consol"))
        self.gridLayout.addWidget(self.consol, 25, 0, 1, 11)
        self.label_5 = QtGui.QLabel(Header)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 27, 0, 1, 1)
        self.function2 = QtGui.QPushButton(Header)
        self.function2.setObjectName(_fromUtf8("function2"))
        self.gridLayout.addWidget(self.function2, 12, 6, 1, 1)
        self.LS = QtGui.QPushButton(Header)
        self.LS.setObjectName(_fromUtf8("LS"))
        self.gridLayout.addWidget(self.LS, 10, 6, 1, 1)
        self.line_2 = QtGui.QFrame(Header)
        self.line_2.setAccessibleName(_fromUtf8(""))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 21, 0, 2, 11)
        self.line = QtGui.QFrame(Header)
        self.line.setAccessibleName(_fromUtf8(""))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 5, 0, 3, 11)
        self.Secret = QtGui.QPushButton(Header)
        self.Secret.setObjectName(_fromUtf8("Secret"))
        self.gridLayout.addWidget(self.Secret, 18, 10, 1, 1)
        self.stackIm = QtGui.QCheckBox(Header)
        self.stackIm.setObjectName(_fromUtf8("stackIm"))
        self.gridLayout.addWidget(self.stackIm, 9, 6, 1, 1)
        self.pathListLabel = QtGui.QLabel(Header)
        self.pathListLabel.setObjectName(_fromUtf8("pathListLabel"))
        self.gridLayout.addWidget(self.pathListLabel, 1, 0, 1, 1)
        self.consolinput = QtGui.QLineEdit(Header)
        self.consolinput.setObjectName(_fromUtf8("consolinput"))
        self.gridLayout.addWidget(self.consolinput, 27, 1, 1, 10)

        self.retranslateUi(Header)
        QtCore.QMetaObject.connectSlotsByName(Header)

    def retranslateUi(self, Header):
        Header.setWindowTitle(_translate("Header", "Basic Spectral Plotter", None))
        self.label.setText(_translate("Header", "Path Files List", None))
        self.label_2.setText(_translate("Header", "Degree:", None))
        self.UserFunction2.setText(_translate("Header", "F2", None))
        self.UseFunction1.setText(_translate("Header", "F1", None))
        self.label_6.setText(_translate("Header", "User Functions", None))
        self.label_3.setText(_translate("Header", "Console Logger", None))
        self.allStack.setText(_translate("Header", "All", None))
        self.userFuntion4.setText(_translate("Header", "F4", None))
        self.UserFuntion3.setText(_translate("Header", "F3", None))
        self.info.setText(_translate("Header", "Info", None))
        self.quitBut.setText(_translate("Header", "Quit", None))
        self.Reset.setText(_translate("Header", "Reload", None))
        self.generatePathFiles.setText(_translate("Header", "Generate Path Files", None))
        self.FunctionFit.setText(_translate("Header", "Fit a Function", None))
        self.StackNumberLabel.setText(_translate("Header", "Stack How Many?", None))
        self.label_4.setText(_translate("Header", "Starting Order Number", None))
        self.singleFileLabel.setText(_translate("Header", "Single File Name", None))
        self.function4.setText(_translate("Header", "G-Fit", None))
        self.function1.setText(_translate("Header", "Show Fit", None))
        self.plotBut.setText(_translate("Header", "Plot", None))
        self.label_5.setText(_translate("Header", "Command >", None))
        self.function2.setText(_translate("Header", "X-Corr", None))
        self.LS.setText(_translate("Header", "LS", None))
        self.Secret.setText(_translate("Header", "Answer", None))
        self.stackIm.setText(_translate("Header", "Stack", None))
        self.pathListLabel.setText(_translate("Header", "Path List File Name", None))

